import type { SamethaluQuestion } from "@shared/types.js";

export const SAMETHALU_QUESTIONS: SamethaluQuestion[] = [
  {
    id: "sq_1",
    proverb: "కుక్క తోక పట్టుకుని ______",
    prompt: "Complete the proverb: కుక్క తోక పట్టుకుని ______",
    options: ["గోదారి ఈదినట్లు", "కొండ ఎక్కినట్లు", "సముద్రం దాటినట్లు", "ఇల్లు చేరినట్లు"],
    correctIndex: 0,
    meaning: "Trying to cross a river by holding a dog's tail — relying on an unreliable or weak support.",
  },
  {
    id: "sq_2",
    proverb: "చేతులు కాలక ______",
    prompt: "Complete the proverb: చేతులు కాలక ______",
    options: ["ఆకులు పట్టుకున్నట్లు", "నీళ్ళు చల్లినట్లు", "మందు రాసినట్లు", "తలుపు వేసినట్లు"],
    correctIndex: 0,
    meaning: "Holding leaves after hands are already burnt — acting too late after damage is done.",
  },
  {
    id: "sq_3",
    proverb: "దీపం ఉండగానే ______",
    prompt: "Complete the proverb: దీపం ఉండగానే ______",
    options: ["ఇల్లు చక్కదిద్దుకోవాలి", "నిద్రపోవాలి", "చదువుకోవాలి", "వంట చేయాలి"],
    correctIndex: 0,
    meaning: "Fix the house while the lamp is still burning — make hay while the sun shines.",
  },
  {
    id: "sq_4",
    proverb: "అందవు ద్రాక్ష పళ్ళు ______",
    prompt: "Complete the proverb: అందవు ద్రాక్ష పళ్ళు ______",
    options: ["పుల్లన", "తీయన", "చేదు", "చల్లన"],
    correctIndex: 0,
    meaning: "Grapes that can't be reached are sour — sour grapes syndrome.",
  },
  {
    id: "sq_5",
    proverb: "మొక్కై వంగనిది ______",
    prompt: "Complete the proverb: మొక్కై వంగనిది ______",
    options: ["మానై వంగునా", "చెట్టై ఎదుగునా", "పువ్వై విరియునా", "కాయై కాచునా"],
    correctIndex: 0,
    meaning: "What does not bend as a sapling will not bend as a tree — habits formed young persist.",
  },
  {
    id: "sq_6",
    proverb: "అడిగేవాడికి చెప్పేవాడు ______",
    prompt: "Complete the proverb: అడిగేవాడికి చెప్పేవాడు ______",
    options: ["లోకువ", "రాజు", "గురువు", "స్నేహితుడు"],
    correctIndex: 0,
    meaning: "The one who answers readily is taken for granted.",
  },
  {
    id: "sq_7",
    proverb: "పిల్లికి చెలగాటం ______",
    prompt: "Complete the proverb: పిల్లికి చెలగాటం ______",
    options: ["ఎలుకకి ప్రాణసంకటం", "కుక్కకి భయం", "కోడికి ఆనందం", "పాముకి కోపం"],
    correctIndex: 0,
    meaning: "What is fun for the cat is life-and-death for the mouse.",
  },
  {
    id: "sq_8",
    proverb: "కూర్చుని తింటే ______",
    prompt: "Complete the proverb: కూర్చుని తింటే ______",
    options: ["కొండలైనా కరిగిపోతాయి", "సంపద పెరుగుతుంది", "ఆరోగ్యం బాగుంటుంది", "సమయం వెళ్తుంది"],
    correctIndex: 0,
    meaning: "Even mountains crumble if eaten away idly without earning.",
  },
  {
    id: "sq_9",
    proverb: "అతి సర్వత్ర ______",
    prompt: "Complete the proverb: అతి సర్వత్ర ______",
    options: ["వర్జయేత్", "పూజయేత్", "గ్రహియేత్", "రంజయేత్"],
    correctIndex: 0,
    meaning: "Excess in anything should be avoided — moderation is key in all matters.",
  },
  {
    id: "sq_10",
    proverb: "అయ్యవారికి చాలు ______",
    prompt: "Complete the proverb: అయ్యవారికి చాలు ______",
    options: ["అంబలి సీసా", "అన్నం గిన్నె", "పాలు గ్లాసు", "నీళ్ళ బిందె"],
    correctIndex: 0,
    meaning: "Simplicity is sufficient for a scholar / contented soul.",
  },
  {
    id: "sq_11",
    proverb: "ఆవు చేలో మేస్తే ______",
    prompt: "Complete the proverb: ఆవు చేలో మేస్తే ______",
    options: ["దూడ గట్టున మేస్తుందా", "దూడ పాలు తాగుతుందా", "దూడ నిద్రపోతుందా", "దూడ పరిగెడుతుందా"],
    correctIndex: 0,
    meaning: "If the mother cow grazes in the crop, will the calf stay on the bund? Children follow parents' actions.",
  },
  {
    id: "sq_12",
    proverb: "ఇంటి దొంగను ______",
    prompt: "Complete the proverb: ఇంటి దొంగను ______",
    options: ["ఈశ్వరుడైనా పట్టలేడు", "రాజైనా పట్టలేడు", "పోలీసైనా పట్టలేడు", "కుక్కైనా పట్టలేడు"],
    correctIndex: 0,
    meaning: "Even God cannot catch an insider thief — betrayal from within is impossible to prevent.",
  },
  {
    id: "sq_13",
    proverb: "ఉపాయం లేని వానికి ______",
    prompt: "Complete the proverb: ఉపాయం లేని వానికి ______",
    options: ["అపాయం తప్పదు", "లాభం రాదు", "స్నేహం దొరకదు", "సంతోషం ఉండదు"],
    correctIndex: 0,
    meaning: "Those without cleverness or resourcefulness cannot avoid danger.",
  },
  {
    id: "sq_14",
    proverb: "ఎద్దు పుండు ______",
    prompt: "Complete the proverb: ఎద్దు పుండు ______",
    options: ["కాకికి ముద్దు", "రైతుకి భయం", "గోడకి రుద్దు", "నీళ్ళలో కడుగు"],
    correctIndex: 0,
    meaning: "An ox's wound is a treat for the crow — one's suffering becomes another's gain.",
  },
  {
    id: "sq_15",
    proverb: "ఏటి ఒడ్డున పండు ______",
    prompt: "Complete the proverb: ఏటి ఒడ్డున పండు ______",
    options: ["ఎప్పుడు రాలుతుందో తెలియదు", "చాలా తియ్యగా ఉంటుంది", "పక్షులు తింటాయి", "నీటిలో పడుతుంది"],
    correctIndex: 0,
    meaning: "Fruit on a river bank can fall anytime — living dangerously near peril.",
  },
  {
    id: "sq_16",
    proverb: "కడప దాటితే ______",
    prompt: "Complete the proverb: కడప దాటితే ______",
    options: ["కావేరి", "గోదావరి", "కృష్ణ", "సముద్రం"],
    correctIndex: 0,
    meaning: "Stepping outside your threshold opens up a vast world.",
  },
  {
    id: "sq_17",
    proverb: "కాకి పిల్ల ______",
    prompt: "Complete the proverb: కాకి పిల్ల ______",
    options: ["కాకికి ముద్దు", "చిలుకకి ముద్దు", "అందరికీ ముద్దు", "ఎవరికీ వద్దు"],
    correctIndex: 0,
    meaning: "A crow's offspring is precious to the crow — every mother loves her child regardless.",
  },
  {
    id: "sq_18",
    proverb: "కొండను తవ్వి ______",
    prompt: "Complete the proverb: కొండను తవ్వి ______",
    options: ["ఎలుకను పట్టినట్లు", "పామును తీసినట్లు", "రాయిని తీసినట్లు", "నీళ్ళు తీసినట్లు"],
    correctIndex: 0,
    meaning: "Digging a mountain to catch a mouse — enormous effort with negligible outcome.",
  },
  {
    id: "sq_19",
    proverb: "కోతికి కొబ్బరికాయ ______",
    prompt: "Complete the proverb: కోతికి కొబ్బరికాయ ______",
    options: ["దొరికినట్లు", "తినిపించినట్లు", "కానుక ఇచ్చినట్లు", "విసిరేసినట్లు"],
    correctIndex: 0,
    meaning: "Giving a coconut to a monkey — giving a valuable item to someone who doesn't know how to use it.",
  },
  {
    id: "sq_20",
    proverb: "గాడిద కేం తెలుసు ______",
    prompt: "Complete the proverb: గాడిద కేం తెలుసు ______",
    options: ["గంధపు పొడి వాసన", "బెల్లం తీపి", "పూల తావి", "తేనె రుచి"],
    correctIndex: 0,
    meaning: "What does a donkey know of sandalwood fragrance? An unrefined person cannot appreciate fine things.",
  },
  {
    id: "sq_21",
    proverb: "గోరు చుట్టు మీద ______",
    prompt: "Complete the proverb: గోరు చుట్టు మీద ______",
    options: ["రోకటి పోటు", "నీటి చుక్క", "మందు పూత", "బ్యాండేజి గుడ్డ"],
    correctIndex: 0,
    meaning: "A pestle blow on an infected fingernail — adding insult to injury / worsening agony.",
  },
  {
    id: "sq_22",
    proverb: "చాప కింద ______",
    prompt: "Complete the proverb: చాప కింద ______",
    options: ["నీరులా", "పాములా", "రాయిలా", "దుమ్ములా"],
    correctIndex: 0,
    meaning: "Like water under a mat — hidden danger or silent creeping influence.",
  },
  {
    id: "sq_23",
    proverb: "చింత చచ్చినా ______",
    prompt: "Complete the proverb: చింత చచ్చినా ______",
    options: ["పులుపు చావదు", "కాయ చావదు", "నీడ చావదు", "కొమ్మ చావదు"],
    correctIndex: 0,
    meaning: "Even if the tamarind tree dies, its sourness remains — core habits persist even when wealth/status fades.",
  },
  {
    id: "sq_24",
    proverb: "నోరు మంచిదైతే ______",
    prompt: "Complete the proverb: నోరు మంచిదైతే ______",
    options: ["ఊరు మంచిదవుతుంది", "ఇల్లు మంచిదవుతుంది", "లోకం మంచిదవుతుంది", "ధనం వస్తుంది"],
    correctIndex: 0,
    meaning: "If your speech is good and polite, the whole town will treat you well.",
  },
  {
    id: "sq_25",
    proverb: "పాముకి పాలు పోసి ______",
    prompt: "Complete the proverb: పాముకి పాలు పోసి ______",
    options: ["పెంచినట్లు", "మొక్కలేసినట్లు", "స్నానం చేయించినట్లు", "పూజించినట్లు"],
    correctIndex: 0,
    meaning: "Nurturing a snake with milk — helping a treacherous person will only backfire.",
  },
  {
    id: "sq_26",
    proverb: "పరిగెత్తి పాలు తాగే కంటే ______",
    prompt: "Complete the proverb: పరిగెత్తి పాలు తాగే కంటే ______",
    options: ["నిలబడి నీళ్ళు తాగడం మేలు", "కూర్చుని కాఫీ తాగడం మేలు", "పండుకోవడం మేలు", "నడవడం మేలు"],
    correctIndex: 0,
    meaning: "Better to drink water standing calmly than run hectically for milk — peace is better than stressful gain.",
  },
  {
    id: "sq_27",
    proverb: "పిలవని పేరంటానికి ______",
    prompt: "Complete the proverb: పిలవని పేరంటానికి ______",
    options: ["వెళ్ళకూడదు", "తొందరపడకూడదు", "బహుమతి ఇవ్వకూడదు", "కోపపడకూడదు"],
    correctIndex: 0,
    meaning: "Do not attend a ceremony without an invitation — self-respect matters.",
  },
  {
    id: "sq_28",
    proverb: "రొట్టె విరిగి ______",
    prompt: "Complete the proverb: రొట్టె విరిగి ______",
    options: ["నేతిలో పడినట్లు", "నీటిలో పడినట్లు", "పాలలో పడినట్లు", "నేలపాలు అయినట్లు"],
    correctIndex: 0,
    meaning: "The bread broke and fell straight into ghee — an unexpectedly fortunate stroke of luck.",
  },
  {
    id: "sq_29",
    proverb: "విత్తనం ఒకటైతే ______",
    prompt: "Complete the proverb: విత్తనం ఒకటైతే ______",
    options: ["మొలక మరొకటవుతుందా", "చెట్టు దొరుకుతుందా", "కాయ కాస్తుందా", "పువ్వు పూస్తుందా"],
    correctIndex: 0,
    meaning: "If the seed is of one type, will the sprout be of another? As you sow, so shall you reap.",
  },
  {
    id: "sq_30",
    proverb: "సంపద ఉన్నప్పుడు ______",
    prompt: "Complete the proverb: సంపద ఉన్నప్పుడు ______",
    options: ["చుట్టాలు వస్తారు", "శత్రువులు వస్తారు", "కష్టాలు వస్తాయి", "నిద్ర వస్తుంది"],
    correctIndex: 0,
    meaning: "Relatives and fair-weather friends swarm around when you have riches.",
  },
];
