import type { TeluguCinemaluPersonality } from "@shared/types.js";

/**
 * Round 1 (Personality) content, organised per subject.
 *
 * Every pool must carry at least one question of each difficulty in
 * TC_ROUND_PLAN's personality mix (easy, easy, moderate, hard, extreme) —
 * `content.test.ts` enforces that, so a half-filled pool fails CI rather than
 * failing a player mid-game.
 *
 * These are hand-authored rather than model-generated: a quiz with a wrong
 * answer key marks a correct player wrong, which is worse than having fewer
 * questions. Facts here are limited to widely documented ones (titles, cast,
 * directors, composers). Anything I could not state with confidence was left
 * out rather than guessed.
 */

const heroes: TeluguCinemaluPersonality[] = [
  {
    id: "p_hero_chiranjeevi",
    role: "hero",
    name: "Chiranjeevi",
    knownFor: "Megastar · Sye Raa, Khaidi No. 150",
    questions: [
      {
        id: "chiru_e1",
        difficulty: "easy",
        prompt: "Which title is Chiranjeevi popularly known by?",
        options: ["Megastar", "Power Star", "Young Tiger", "Rebel Star"],
        correctIndex: 0,
      },
      {
        id: "chiru_e2",
        difficulty: "easy",
        prompt: "Chiranjeevi played the freedom fighter Uyyalawada Narasimha Reddy in which film?",
        options: ["Sye Raa Narasimha Reddy", "Khaidi No. 150", "Acharya", "Godfather"],
        correctIndex: 0,
      },
      {
        id: "chiru_m1",
        difficulty: "moderate",
        prompt: "Who directed Khaidi No. 150, Chiranjeevi's comeback film?",
        options: ["V. V. Vinayak", "Puri Jagannadh", "Koratala Siva", "Boyapati Srinu"],
        correctIndex: 0,
      },
      {
        id: "chiru_h1",
        difficulty: "hard",
        prompt: "Khaidi No. 150 is the Telugu remake of which Tamil film?",
        options: ["Kaththi", "Thuppakki", "Theri", "Mersal"],
        correctIndex: 0,
        trivia: "Kaththi starred Vijay and was directed by A. R. Murugadoss.",
      },
      {
        id: "chiru_x1",
        difficulty: "extreme",
        prompt: "What is Chiranjeevi's birth name?",
        options: [
          "Konidela Siva Sankara Vara Prasad",
          "Konidela Kalyan Babu",
          "Ghattamaneni Mahesh",
          "Akkineni Nageswara Rao",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_hero_mahesh",
    role: "hero",
    name: "Mahesh Babu",
    knownFor: "Superstar · Pokiri, Srimanthudu",
    questions: [
      {
        id: "mahesh_e1",
        difficulty: "easy",
        prompt: "The dialogue \"Okkasari commit ayithe naa maata nenae vinanu\" is from which Mahesh Babu film?",
        options: ["Pokiri", "Dookudu", "Athadu", "Businessman"],
        correctIndex: 0,
      },
      {
        id: "mahesh_e2",
        difficulty: "easy",
        prompt: "Mahesh Babu's father is which veteran Telugu actor?",
        options: ["Krishna", "Krishnam Raju", "Murali Mohan", "Kaikala Satyanarayana"],
        correctIndex: 0,
      },
      {
        id: "mahesh_m1",
        difficulty: "moderate",
        prompt: "Who directed Srimanthudu?",
        options: ["Koratala Siva", "Trivikram Srinivas", "Srinu Vaitla", "Anil Ravipudi"],
        correctIndex: 0,
      },
      {
        id: "mahesh_h1",
        difficulty: "hard",
        prompt: "Who directed Dookudu?",
        options: ["Srinu Vaitla", "Puri Jagannadh", "Harish Shankar", "Vamshi Paidipally"],
        correctIndex: 0,
      },
      {
        id: "mahesh_x1",
        difficulty: "extreme",
        prompt: "Which 1999 film was Mahesh Babu's first as a lead hero?",
        options: ["Raja Kumarudu", "Yuvaraju", "Murari", "Vamsi"],
        correctIndex: 0,
        trivia: "He had appeared as a child artist in several films before this.",
      },
    ],
  },
  {
    id: "p_hero_pawan",
    role: "hero",
    name: "Pawan Kalyan",
    knownFor: "Power Star · Gabbar Singh, Attarintiki Daredi",
    questions: [
      {
        id: "pawan_e1",
        difficulty: "easy",
        prompt: "\"Naaku konchem thikkundi, kaani daaniko lekkundi\" is from which film?",
        options: ["Gabbar Singh", "Attarintiki Daredi", "Jalsa", "Kushi"],
        correctIndex: 0,
      },
      {
        id: "pawan_e2",
        difficulty: "easy",
        prompt: "Pawan Kalyan's elder brother is which Telugu superstar?",
        options: ["Chiranjeevi", "Nagarjuna", "Venkatesh", "Balakrishna"],
        correctIndex: 0,
      },
      {
        id: "pawan_m1",
        difficulty: "moderate",
        prompt: "Who directed Attarintiki Daredi?",
        options: ["Trivikram Srinivas", "Harish Shankar", "Puri Jagannadh", "Koratala Siva"],
        correctIndex: 0,
      },
      {
        id: "pawan_h1",
        difficulty: "hard",
        prompt: "Gabbar Singh is the Telugu remake of which Hindi film?",
        options: ["Dabangg", "Wanted", "Singham", "Rowdy Rathore"],
        correctIndex: 0,
      },
      {
        id: "pawan_x1",
        difficulty: "extreme",
        prompt: "What is Pawan Kalyan's birth name?",
        options: [
          "Konidela Kalyan Babu",
          "Konidela Siva Sankara Vara Prasad",
          "Nandamuri Taraka Rama Rao",
          "Uppalapati Venkata Suryanarayana Prabhas Raju",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_hero_alluarjun",
    role: "hero",
    name: "Allu Arjun",
    knownFor: "Icon Star · Pushpa, Ala Vaikunthapurramuloo",
    questions: [
      {
        id: "aa_e1",
        difficulty: "easy",
        prompt: "The catchphrase \"Thaggedhe le\" comes from which Allu Arjun film?",
        options: ["Pushpa: The Rise", "Ala Vaikunthapurramuloo", "Race Gurram", "Sarrainodu"],
        correctIndex: 0,
      },
      {
        id: "aa_e2",
        difficulty: "easy",
        prompt: "Who directed Pushpa: The Rise?",
        options: ["Sukumar", "Trivikram Srinivas", "Boyapati Srinu", "Harish Shankar"],
        correctIndex: 0,
      },
      {
        id: "aa_m1",
        difficulty: "moderate",
        prompt: "Who directed Ala Vaikunthapurramuloo?",
        options: ["Trivikram Srinivas", "Sukumar", "Vamshi Paidipally", "Koratala Siva"],
        correctIndex: 0,
      },
      {
        id: "aa_h1",
        difficulty: "hard",
        prompt: "Which 2003 film was Allu Arjun's first as a lead hero?",
        options: ["Gangotri", "Arya", "Bunny", "Happy"],
        correctIndex: 0,
      },
      {
        id: "aa_x1",
        difficulty: "extreme",
        prompt: "For which film did Allu Arjun win the National Film Award for Best Actor?",
        options: ["Pushpa: The Rise", "Rangasthalam", "Arya 2", "Ala Vaikunthapurramuloo"],
        correctIndex: 0,
        trivia: "It was the first National Best Actor award for a Telugu-language performance.",
      },
    ],
  },
  {
    id: "p_hero_ntr",
    role: "hero",
    name: "N. T. Rama Rao Jr.",
    knownFor: "Young Tiger · RRR, Simhadri",
    questions: [
      {
        id: "ntr_e1",
        difficulty: "easy",
        prompt: "Which character did NTR Jr. play in RRR?",
        options: ["Komaram Bheem", "Alluri Sitarama Raju", "Baahubali", "Bhallaladeva"],
        correctIndex: 0,
      },
      {
        id: "ntr_e2",
        difficulty: "easy",
        prompt: "Who starred alongside NTR Jr. as the second lead in RRR?",
        options: ["Ram Charan", "Prabhas", "Allu Arjun", "Mahesh Babu"],
        correctIndex: 0,
      },
      {
        id: "ntr_m1",
        difficulty: "moderate",
        prompt: "Who directed Simhadri?",
        options: ["S. S. Rajamouli", "Boyapati Srinu", "Puri Jagannadh", "Surender Reddy"],
        correctIndex: 0,
      },
      {
        id: "ntr_h1",
        difficulty: "hard",
        prompt: "Which 2001 film was both S. S. Rajamouli's directorial debut and an early NTR Jr. hit?",
        options: ["Student No. 1", "Simhadri", "Yamadonga", "Aadi"],
        correctIndex: 0,
      },
      {
        id: "ntr_x1",
        difficulty: "extreme",
        prompt: "NTR Jr.'s grandfather was which legendary actor and Chief Minister of Andhra Pradesh?",
        options: ["N. T. Rama Rao", "Akkineni Nageswara Rao", "S. V. Ranga Rao", "Krishna"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_hero_prabhas",
    role: "hero",
    name: "Prabhas",
    knownFor: "Rebel Star · Baahubali, Mirchi",
    questions: [
      {
        id: "prabhas_e1",
        difficulty: "easy",
        prompt: "Who directed the Baahubali films?",
        options: ["S. S. Rajamouli", "Koratala Siva", "Sukumar", "Trivikram Srinivas"],
        correctIndex: 0,
      },
      {
        id: "prabhas_e2",
        difficulty: "easy",
        prompt: "Prabhas played a dual role in Baahubali. Which two characters?",
        options: [
          "Amarendra Baahubali and Mahendra Baahubali",
          "Bhallaladeva and Kattappa",
          "Baahubali and Bhallaladeva",
          "Kattappa and Bijjaladeva",
        ],
        correctIndex: 0,
      },
      {
        id: "prabhas_m1",
        difficulty: "moderate",
        prompt: "Which Prabhas film was Koratala Siva's directorial debut?",
        options: ["Mirchi", "Srimanthudu", "Janatha Garage", "Bharat Ane Nenu"],
        correctIndex: 0,
      },
      {
        id: "prabhas_h1",
        difficulty: "hard",
        prompt: "Who directed Chatrapathi (2005), starring Prabhas?",
        options: ["S. S. Rajamouli", "Puri Jagannadh", "V. V. Vinayak", "Boyapati Srinu"],
        correctIndex: 0,
      },
      {
        id: "prabhas_x1",
        difficulty: "extreme",
        prompt: "Prabhas's uncle, a veteran actor and producer, was known as the original Rebel Star. Who?",
        options: ["Krishnam Raju", "Krishna", "Sobhan Babu", "Kaikala Satyanarayana"],
        correctIndex: 0,
      },
    ],
  },
];

const heroines: TeluguCinemaluPersonality[] = [
  {
    id: "p_heroine_anushka",
    role: "heroine",
    name: "Anushka Shetty",
    knownFor: "Arundhati, Baahubali",
    questions: [
      {
        id: "anu_e1",
        difficulty: "easy",
        prompt: "Which character did Anushka Shetty play in the Baahubali films?",
        options: ["Devasena", "Avanthika", "Sivagami", "Rama Lakshmi"],
        correctIndex: 0,
      },
      {
        id: "anu_e2",
        difficulty: "easy",
        prompt: "Which 2009 fantasy hit featured Anushka in a dual role as Jejamma and Arundhati?",
        options: ["Arundhati", "Rudhramadevi", "Bhaagamathie", "Anaganaga O Dheerudu"],
        correctIndex: 0,
      },
      {
        id: "anu_m1",
        difficulty: "moderate",
        prompt: "Who directed Arundhati?",
        options: ["Kodi Ramakrishna", "S. S. Rajamouli", "Gunasekhar", "Puri Jagannadh"],
        correctIndex: 0,
      },
      {
        id: "anu_h1",
        difficulty: "hard",
        prompt: "Anushka starred opposite Prabhas in which Koratala Siva film?",
        options: ["Mirchi", "Billa", "Mr. Perfect", "Panchakshari"],
        correctIndex: 0,
      },
      {
        id: "anu_x1",
        difficulty: "extreme",
        prompt: "What is Anushka Shetty's birth name?",
        options: ["Sweety Shetty", "Anushka Rao", "Sweety Nanda", "Anushka Reddy"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_heroine_samantha",
    role: "heroine",
    name: "Samantha",
    knownFor: "Ye Maaya Chesave, Rangasthalam",
    questions: [
      {
        id: "sam_e1",
        difficulty: "easy",
        prompt: "Which film was Samantha's Telugu debut, opposite Naga Chaitanya?",
        options: ["Ye Maaya Chesave", "Dookudu", "Eega", "Attarintiki Daredi"],
        correctIndex: 0,
      },
      {
        id: "sam_e2",
        difficulty: "easy",
        prompt: "Who directed Rangasthalam, in which Samantha played Rama Lakshmi?",
        options: ["Sukumar", "Trivikram Srinivas", "Koratala Siva", "Sekhar Kammula"],
        correctIndex: 0,
      },
      {
        id: "sam_m1",
        difficulty: "moderate",
        prompt: "Who directed Ye Maaya Chesave?",
        options: [
          "Gautham Vasudev Menon",
          "Sekhar Kammula",
          "Nandini Reddy",
          "Vamshi Paidipally",
        ],
        correctIndex: 0,
      },
      {
        id: "sam_h1",
        difficulty: "hard",
        prompt: "Who composed the music for Ye Maaya Chesave?",
        options: ["A. R. Rahman", "Devi Sri Prasad", "Thaman S", "Mickey J Meyer"],
        correctIndex: 0,
      },
      {
        id: "sam_x1",
        difficulty: "extreme",
        prompt: "What was the name of Samantha's character in Rangasthalam?",
        options: ["Rama Lakshmi", "Devasena", "Sasirekha", "Bhanumathi"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_heroine_kajal",
    role: "heroine",
    name: "Kajal Aggarwal",
    knownFor: "Magadheera, Dhada",
    questions: [
      {
        id: "kaj_e1",
        difficulty: "easy",
        prompt: "Kajal Aggarwal starred opposite Ram Charan in which Rajamouli reincarnation epic?",
        options: ["Magadheera", "Eega", "Yamadonga", "Vikramarkudu"],
        correctIndex: 0,
      },
      {
        id: "kaj_e2",
        difficulty: "easy",
        prompt: "Who directed Magadheera?",
        options: ["S. S. Rajamouli", "V. V. Vinayak", "Gunasekhar", "Puri Jagannadh"],
        correctIndex: 0,
      },
      {
        id: "kaj_m1",
        difficulty: "moderate",
        prompt: "Who composed the music for Magadheera?",
        options: ["M. M. Keeravani", "Devi Sri Prasad", "Mani Sharma", "Thaman S"],
        correctIndex: 0,
      },
      {
        id: "kaj_h1",
        difficulty: "hard",
        prompt: "Kajal starred opposite Naga Chaitanya in which 2011 film scored by Devi Sri Prasad?",
        options: ["Dhada", "100% Love", "Josh", "Bejawada"],
        correctIndex: 0,
      },
      {
        id: "kaj_x1",
        difficulty: "extreme",
        prompt: "Which 2007 film marked Kajal Aggarwal's Telugu debut?",
        options: ["Lakshmi Kalyanam", "Chandamama", "Magadheera", "Darling"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_heroine_tamannaah",
    role: "heroine",
    name: "Tamannaah",
    knownFor: "Baahubali, 100% Love",
    questions: [
      {
        id: "tam_e1",
        difficulty: "easy",
        prompt: "Which warrior did Tamannaah play in Baahubali: The Beginning?",
        options: ["Avanthika", "Devasena", "Sivagami", "Nassar"],
        correctIndex: 0,
      },
      {
        id: "tam_e2",
        difficulty: "easy",
        prompt: "Tamannaah starred opposite Naga Chaitanya in which 2011 Sukumar film?",
        options: ["100% Love", "Dhada", "Ye Maaya Chesave", "Autonagar Surya"],
        correctIndex: 0,
      },
      {
        id: "tam_m1",
        difficulty: "moderate",
        prompt: "Who directed 100% Love?",
        options: ["Sukumar", "Trivikram Srinivas", "Gautham Menon", "Puri Jagannadh"],
        correctIndex: 0,
      },
      {
        id: "tam_h1",
        difficulty: "hard",
        prompt: "Tamannaah starred opposite Allu Arjun in which 2011 V. V. Vinayak film?",
        options: ["Badrinath", "Race Gurram", "Julayi", "Iddarammayilatho"],
        correctIndex: 0,
      },
      {
        id: "tam_x1",
        difficulty: "extreme",
        prompt: "Which 2005 film marked Tamannaah's Telugu debut?",
        options: ["Sri", "Kalidasu", "Happy Days", "Konchem Ishtam Konchem Kashtam"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_heroine_rashmika",
    role: "heroine",
    name: "Rashmika Mandanna",
    knownFor: "Pushpa, Geetha Govindam",
    questions: [
      {
        id: "rash_e1",
        difficulty: "easy",
        prompt: "Rashmika played Srivalli in which blockbuster?",
        options: ["Pushpa: The Rise", "Geetha Govindam", "Dear Comrade", "Sarileru Neekevvaru"],
        correctIndex: 0,
      },
      {
        id: "rash_e2",
        difficulty: "easy",
        prompt: "Which 2018 romantic comedy paired Rashmika with Vijay Deverakonda?",
        options: ["Geetha Govindam", "Pushpa: The Rise", "Bheeshma", "Chalo"],
        correctIndex: 0,
      },
      {
        id: "rash_m1",
        difficulty: "moderate",
        prompt: "Who directed Geetha Govindam?",
        options: ["Parasuram", "Sukumar", "Anil Ravipudi", "Bharat Kamma"],
        correctIndex: 0,
      },
      {
        id: "rash_h1",
        difficulty: "hard",
        prompt: "Rashmika starred opposite Mahesh Babu in which 2020 Anil Ravipudi film?",
        options: ["Sarileru Neekevvaru", "Bharat Ane Nenu", "Maharshi", "Spyder"],
        correctIndex: 0,
      },
      {
        id: "rash_x1",
        difficulty: "extreme",
        prompt: "Which 2019 film paired Rashmika with Vijay Deverakonda a second time?",
        options: ["Dear Comrade", "Geetha Govindam", "World Famous Lover", "Taxiwaala"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_heroine_saipallavi",
    role: "heroine",
    name: "Sai Pallavi",
    knownFor: "Fidaa, Love Story",
    questions: [
      {
        id: "sp_e1",
        difficulty: "easy",
        prompt: "Sai Pallavi played Bhanumathi in which 2017 film opposite Varun Tej?",
        options: ["Fidaa", "Love Story", "Padi Padi Leche Manasu", "Shyam Singha Roy"],
        correctIndex: 0,
      },
      {
        id: "sp_e2",
        difficulty: "easy",
        prompt: "Who directed Fidaa?",
        options: ["Sekhar Kammula", "Trivikram Srinivas", "Nandini Reddy", "Hanu Raghavapudi"],
        correctIndex: 0,
      },
      {
        id: "sp_m1",
        difficulty: "moderate",
        prompt: "Sai Pallavi reunited with Sekhar Kammula opposite Naga Chaitanya in which 2021 film?",
        options: ["Love Story", "Fidaa", "Majili", "Thank You"],
        correctIndex: 0,
      },
      {
        id: "sp_h1",
        difficulty: "hard",
        prompt: "Sai Pallavi starred opposite Nani in which 2021 period drama?",
        options: ["Shyam Singha Roy", "Jersey", "Gang Leader", "V"],
        correctIndex: 0,
      },
      {
        id: "sp_x1",
        difficulty: "extreme",
        prompt: "Sai Pallavi made her acting debut in which 2015 Malayalam film?",
        options: ["Premam", "Kali", "Charlie", "Bangalore Days"],
        correctIndex: 0,
        trivia: "She played Malar, a role that made her a household name across South India.",
      },
    ],
  },
];

const directors: TeluguCinemaluPersonality[] = [
  {
    id: "p_dir_rajamouli",
    role: "director",
    name: "S. S. Rajamouli",
    knownFor: "Baahubali, RRR",
    questions: [
      {
        id: "raja_e1",
        difficulty: "easy",
        prompt: "Which two-part epic did S. S. Rajamouli direct?",
        options: ["Baahubali", "Pushpa", "KGF", "Rangasthalam"],
        correctIndex: 0,
      },
      {
        id: "raja_e2",
        difficulty: "easy",
        prompt: "Which two heroes led Rajamouli's RRR?",
        options: [
          "NTR Jr. and Ram Charan",
          "Prabhas and Rana Daggubati",
          "Allu Arjun and Mahesh Babu",
          "Pawan Kalyan and Nani",
        ],
        correctIndex: 0,
      },
      {
        id: "raja_m1",
        difficulty: "moderate",
        prompt: "In which Rajamouli film is the hero reincarnated as a housefly?",
        options: ["Eega", "Magadheera", "Yamadonga", "Maryada Ramanna"],
        correctIndex: 0,
      },
      {
        id: "raja_h1",
        difficulty: "hard",
        prompt: "Rajamouli's father, who wrote several of his films, is which screenwriter?",
        options: ["V. Vijayendra Prasad", "M. M. Keeravani", "Paruchuri Venkateswara Rao", "Satyanand"],
        correctIndex: 0,
      },
      {
        id: "raja_x1",
        difficulty: "extreme",
        prompt: "Which 2001 film was Rajamouli's directorial debut?",
        options: ["Student No. 1", "Simhadri", "Sye", "Chatrapathi"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_dir_trivikram",
    role: "director",
    name: "Trivikram Srinivas",
    knownFor: "Attarintiki Daredi, Ala Vaikunthapurramuloo",
    questions: [
      {
        id: "tri_e1",
        difficulty: "easy",
        prompt: "Which Pawan Kalyan blockbuster about a grandson reuniting a family did Trivikram direct?",
        options: ["Attarintiki Daredi", "Gabbar Singh", "Jalsa", "Sardaar Gabbar Singh"],
        correctIndex: 0,
      },
      {
        id: "tri_e2",
        difficulty: "easy",
        prompt: "Who starred in Trivikram's Ala Vaikunthapurramuloo?",
        options: ["Allu Arjun", "Mahesh Babu", "NTR Jr.", "Ram Charan"],
        correctIndex: 0,
      },
      {
        id: "tri_m1",
        difficulty: "moderate",
        prompt: "Which 2010 Mahesh Babu film did Trivikram direct?",
        options: ["Khaleja", "Dookudu", "Businessman", "Srimanthudu"],
        correctIndex: 0,
      },
      {
        id: "tri_h1",
        difficulty: "hard",
        prompt: "Trivikram is widely nicknamed what, in tribute to his dialogue writing?",
        options: ["Guruji", "Rockstar", "Director's Director", "Wordsmith"],
        correctIndex: 0,
      },
      {
        id: "tri_x1",
        difficulty: "extreme",
        prompt: "Which 2002 film starring Tarun was Trivikram's directorial debut?",
        options: ["Nuvve Nuvve", "Athadu", "Malliswari", "Jalsa"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_dir_sukumar",
    role: "director",
    name: "Sukumar",
    knownFor: "Pushpa, Rangasthalam",
    questions: [
      {
        id: "suku_e1",
        difficulty: "easy",
        prompt: "Which Sukumar film follows a red sandalwood smuggler?",
        options: ["Pushpa: The Rise", "Rangasthalam", "Arya", "Nannaku Prematho"],
        correctIndex: 0,
      },
      {
        id: "suku_e2",
        difficulty: "easy",
        prompt: "Who played the partially deaf Chitti Babu in Sukumar's Rangasthalam?",
        options: ["Ram Charan", "Allu Arjun", "NTR Jr.", "Nani"],
        correctIndex: 0,
      },
      {
        id: "suku_m1",
        difficulty: "moderate",
        prompt: "Which 2004 film starring Allu Arjun was Sukumar's directorial debut?",
        options: ["Arya", "Bunny", "Jagadam", "100% Love"],
        correctIndex: 0,
      },
      {
        id: "suku_h1",
        difficulty: "hard",
        prompt: "Which 2016 NTR Jr. film did Sukumar direct?",
        options: ["Nannaku Prematho", "Janatha Garage", "Temper", "Aravinda Sametha"],
        correctIndex: 0,
      },
      {
        id: "suku_x1",
        difficulty: "extreme",
        prompt: "What was Sukumar's profession before he entered films?",
        options: [
          "Mathematics lecturer",
          "Newspaper journalist",
          "Civil engineer",
          "Stage actor",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_dir_koratala",
    role: "director",
    name: "Koratala Siva",
    knownFor: "Srimanthudu, Bharat Ane Nenu",
    questions: [
      {
        id: "kor_e1",
        difficulty: "easy",
        prompt: "Who starred in Koratala Siva's Srimanthudu?",
        options: ["Mahesh Babu", "Prabhas", "NTR Jr.", "Ram Charan"],
        correctIndex: 0,
      },
      {
        id: "kor_e2",
        difficulty: "easy",
        prompt: "In Bharat Ane Nenu, Mahesh Babu's character becomes what?",
        options: [
          "Chief Minister",
          "Police Commissioner",
          "Army officer",
          "Village sarpanch",
        ],
        correctIndex: 0,
      },
      {
        id: "kor_m1",
        difficulty: "moderate",
        prompt: "Which Prabhas film was Koratala Siva's directorial debut?",
        options: ["Mirchi", "Chatrapathi", "Mr. Perfect", "Billa"],
        correctIndex: 0,
      },
      {
        id: "kor_h1",
        difficulty: "hard",
        prompt: "Which 2016 NTR Jr. film did Koratala Siva direct?",
        options: ["Janatha Garage", "Nannaku Prematho", "Jai Lava Kusa", "Temper"],
        correctIndex: 0,
      },
      {
        id: "kor_x1",
        difficulty: "extreme",
        prompt: "Which 2022 Chiranjeevi film did Koratala Siva direct?",
        options: ["Acharya", "Godfather", "Waltair Veerayya", "Bholaa Shankar"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_dir_puri",
    role: "director",
    name: "Puri Jagannadh",
    knownFor: "Pokiri, Businessman",
    questions: [
      {
        id: "puri_e1",
        difficulty: "easy",
        prompt: "Which Mahesh Babu blockbuster did Puri Jagannadh direct in 2006?",
        options: ["Pokiri", "Athadu", "Dookudu", "Khaleja"],
        correctIndex: 0,
      },
      {
        id: "puri_e2",
        difficulty: "easy",
        prompt: "Which 2012 Mahesh Babu film did Puri Jagannadh direct?",
        options: ["Businessman", "Srimanthudu", "Aagadu", "Spyder"],
        correctIndex: 0,
      },
      {
        id: "puri_m1",
        difficulty: "moderate",
        prompt: "Which 2022 pan-India film with Vijay Deverakonda did Puri Jagannadh direct?",
        options: ["Liger", "Arjun Reddy", "Dear Comrade", "Taxiwaala"],
        correctIndex: 0,
      },
      {
        id: "puri_h1",
        difficulty: "hard",
        prompt: "Which 2002 Ravi Teja film gave Puri Jagannadh his breakthrough?",
        options: ["Idiot", "Itlu Sravani Subramanyam", "Amma Nanna O Tamila Ammayi", "Neninthe"],
        correctIndex: 0,
      },
      {
        id: "puri_x1",
        difficulty: "extreme",
        prompt: "Pokiri was remade in Hindi under which title?",
        options: ["Wanted", "Ghajini", "Rowdy Rathore", "Singham"],
        correctIndex: 0,
        trivia: "The Hindi remake starred Salman Khan and revived his box-office run.",
      },
    ],
  },
  {
    id: "p_dir_sekhar",
    role: "director",
    name: "Sekhar Kammula",
    knownFor: "Fidaa, Happy Days",
    questions: [
      {
        id: "sek_e1",
        difficulty: "easy",
        prompt: "Which 2017 film starring Sai Pallavi and Varun Tej did Sekhar Kammula direct?",
        options: ["Fidaa", "Love Story", "Godavari", "Anand"],
        correctIndex: 0,
      },
      {
        id: "sek_e2",
        difficulty: "easy",
        prompt: "Which 2007 Sekhar Kammula film follows a group of engineering students?",
        options: ["Happy Days", "Godavari", "Life Is Beautiful", "Anand"],
        correctIndex: 0,
      },
      {
        id: "sek_m1",
        difficulty: "moderate",
        prompt: "Which 2006 Sekhar Kammula film starred Sumanth and Kamalinee Mukherjee?",
        options: ["Godavari", "Anand", "Happy Days", "Leader"],
        correctIndex: 0,
      },
      {
        id: "sek_h1",
        difficulty: "hard",
        prompt: "Sekhar Kammula's Love Story (2021) paired Sai Pallavi with which actor?",
        options: ["Naga Chaitanya", "Varun Tej", "Nani", "Vijay Deverakonda"],
        correctIndex: 0,
      },
      {
        id: "sek_x1",
        difficulty: "extreme",
        prompt: "Which 2004 film was Sekhar Kammula's Telugu breakthrough?",
        options: ["Anand", "Godavari", "Dollar Dreams", "Happy Days"],
        correctIndex: 0,
      },
    ],
  },
];

const musicDirectors: TeluguCinemaluPersonality[] = [
  {
    id: "p_mus_keeravani",
    role: "musicDirector",
    name: "M. M. Keeravani",
    knownFor: "Baahubali, RRR",
    questions: [
      {
        id: "keer_e1",
        difficulty: "easy",
        prompt: "Who composed the music for the Baahubali films?",
        options: ["M. M. Keeravani", "Devi Sri Prasad", "Thaman S", "Mani Sharma"],
        correctIndex: 0,
      },
      {
        id: "keer_e2",
        difficulty: "easy",
        prompt: "Keeravani's \"Naatu Naatu\" from RRR won which major international award?",
        options: [
          "Academy Award for Best Original Song",
          "Grammy for Song of the Year",
          "BAFTA for Best Music",
          "Palme d'Or",
        ],
        correctIndex: 0,
      },
      {
        id: "keer_m1",
        difficulty: "moderate",
        prompt: "M. M. Keeravani is a cousin of which director?",
        options: ["S. S. Rajamouli", "Sukumar", "Trivikram Srinivas", "Puri Jagannadh"],
        correctIndex: 0,
      },
      {
        id: "keer_h1",
        difficulty: "hard",
        prompt: "Which 2012 NTR Jr. film starring Trisha did Keeravani score?",
        options: ["Dammu", "Baadshah", "Rabhasa", "Ramayya Vasthavayya"],
        correctIndex: 0,
      },
      {
        id: "keer_x1",
        difficulty: "extreme",
        prompt: "Under what name has M. M. Keeravani composed for Hindi films?",
        options: ["M. M. Kreem", "Maragathamani", "M. M. Raja", "Keeravani Rao"],
        correctIndex: 0,
        trivia: "He is credited as Maragathamani for some Tamil films and M. M. Kreem in Hindi.",
      },
    ],
  },
  {
    id: "p_mus_dsp",
    role: "musicDirector",
    name: "Devi Sri Prasad",
    knownFor: "Pushpa, Rangasthalam",
    questions: [
      {
        id: "dsp_e1",
        difficulty: "easy",
        prompt: "Who composed the music for Pushpa: The Rise?",
        options: ["Devi Sri Prasad", "Thaman S", "M. M. Keeravani", "Anirudh Ravichander"],
        correctIndex: 0,
      },
      {
        id: "dsp_e2",
        difficulty: "easy",
        prompt: "Devi Sri Prasad is popularly known by which nickname?",
        options: ["Rockstar", "Guruji", "Maestro", "Isaignani"],
        correctIndex: 0,
      },
      {
        id: "dsp_m1",
        difficulty: "moderate",
        prompt: "Who composed the music for Sukumar's Rangasthalam?",
        options: ["Devi Sri Prasad", "M. M. Keeravani", "Mickey J Meyer", "Thaman S"],
        correctIndex: 0,
      },
      {
        id: "dsp_h1",
        difficulty: "hard",
        prompt: "Which 2011 film starring Naga Chaitanya and Kajal Aggarwal did DSP score?",
        options: ["Dhada", "100% Love", "Bejawada", "Josh"],
        correctIndex: 0,
      },
      {
        id: "dsp_x1",
        difficulty: "extreme",
        prompt: "Devi Sri Prasad's elder brother, also active in Telugu cinema, is who?",
        options: ["Sagar", "Chakri", "Anup Rubens", "Kalyani Malik"],
        correctIndex: 0,
        trivia: "Their father, Gottumukkala Sathyamurthy, was a noted writer and lyricist.",
      },
    ],
  },
  {
    id: "p_mus_thaman",
    role: "musicDirector",
    name: "Thaman S",
    knownFor: "Ala Vaikunthapurramuloo, Dookudu",
    questions: [
      {
        id: "tha_e1",
        difficulty: "easy",
        prompt: "Who composed the music for Ala Vaikunthapurramuloo?",
        options: ["Thaman S", "Devi Sri Prasad", "Anirudh Ravichander", "Mickey J Meyer"],
        correctIndex: 0,
      },
      {
        id: "tha_e2",
        difficulty: "easy",
        prompt: "Which 2011 Mahesh Babu blockbuster did Thaman score?",
        options: ["Dookudu", "Pokiri", "Athadu", "Businessman"],
        correctIndex: 0,
      },
      {
        id: "tha_m1",
        difficulty: "moderate",
        prompt: "Which 2014 Allu Arjun film did Thaman score?",
        options: ["Race Gurram", "Julayi", "Sarrainodu", "Iddarammayilatho"],
        correctIndex: 0,
      },
      {
        id: "tha_h1",
        difficulty: "hard",
        prompt: "Thaman scored Sarkaru Vaari Paata (2022), which starred whom?",
        options: ["Mahesh Babu", "Allu Arjun", "Ram Charan", "NTR Jr."],
        correctIndex: 0,
      },
      {
        id: "tha_x1",
        difficulty: "extreme",
        prompt: "Thaman began his career in films as what, before becoming a composer?",
        options: ["A percussionist", "A playback singer", "A lyricist", "A sound engineer"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_mus_manisharma",
    role: "musicDirector",
    name: "Mani Sharma",
    knownFor: "Pokiri, Athadu",
    questions: [
      {
        id: "mani_e1",
        difficulty: "easy",
        prompt: "Who composed the music for Pokiri?",
        options: ["Mani Sharma", "Devi Sri Prasad", "Thaman S", "M. M. Keeravani"],
        correctIndex: 0,
      },
      {
        id: "mani_e2",
        difficulty: "easy",
        prompt: "Which Trivikram-directed Mahesh Babu film did Mani Sharma score in 2005?",
        options: ["Athadu", "Dookudu", "Khaleja", "Businessman"],
        correctIndex: 0,
      },
      {
        id: "mani_m1",
        difficulty: "moderate",
        prompt: "Which 2001 Pawan Kalyan romantic hit did Mani Sharma score?",
        options: ["Kushi", "Jalsa", "Gabbar Singh", "Tholi Prema"],
        correctIndex: 0,
      },
      {
        id: "mani_h1",
        difficulty: "hard",
        prompt: "Which 1998 Chiranjeevi film did Mani Sharma score?",
        options: ["Choodalani Vundi", "Indra", "Tagore", "Annayya"],
        correctIndex: 0,
      },
      {
        id: "mani_x1",
        difficulty: "extreme",
        prompt: "Mani Sharma's son is also a Telugu film composer. Under what name does he work?",
        options: ["Mahati Swara Sagar", "Anup Rubens", "Gopi Sundar", "Sricharan Pakala"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_mus_mickey",
    role: "musicDirector",
    name: "Mickey J Meyer",
    knownFor: "Happy Days, Seethamma Vakitlo Sirimalle Chettu",
    questions: [
      {
        id: "mic_e1",
        difficulty: "easy",
        prompt: "Who composed the music for Sekhar Kammula's Happy Days?",
        options: ["Mickey J Meyer", "Devi Sri Prasad", "Mani Sharma", "Thaman S"],
        correctIndex: 0,
      },
      {
        id: "mic_e2",
        difficulty: "easy",
        prompt: "Happy Days is set in which kind of institution?",
        options: ["An engineering college", "A medical college", "A boarding school", "A law college"],
        correctIndex: 0,
      },
      {
        id: "mic_m1",
        difficulty: "moderate",
        prompt: "Which 2008 film, Sreekanth Addala's directorial debut, did Mickey J Meyer score?",
        options: ["Kotha Bangaru Lokam", "Happy Days", "Godavari", "Ashta Chamma"],
        correctIndex: 0,
      },
      {
        id: "mic_h1",
        difficulty: "hard",
        prompt: "Which 2013 Sreekanth Addala family drama did Mickey J Meyer score?",
        options: [
          "Seethamma Vakitlo Sirimalle Chettu",
          "Manam",
          "Attarintiki Daredi",
          "Mukunda",
        ],
        correctIndex: 0,
      },
      {
        id: "mic_x1",
        difficulty: "extreme",
        prompt: "Which two heroes led Seethamma Vakitlo Sirimalle Chettu?",
        options: [
          "Mahesh Babu and Venkatesh",
          "Mahesh Babu and Nagarjuna",
          "Venkatesh and Ram Charan",
          "Nagarjuna and Naga Chaitanya",
        ],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "p_mus_anirudh",
    role: "musicDirector",
    name: "Anirudh Ravichander",
    knownFor: "Jersey, Agnyaathavaasi",
    questions: [
      {
        id: "ani_e1",
        difficulty: "easy",
        prompt: "Who composed the music for the Telugu film Jersey (2019)?",
        options: ["Anirudh Ravichander", "Thaman S", "Devi Sri Prasad", "Mickey J Meyer"],
        correctIndex: 0,
      },
      {
        id: "ani_e2",
        difficulty: "easy",
        prompt: "Jersey (2019) starred which actor as an ageing cricketer?",
        options: ["Nani", "Naga Chaitanya", "Varun Tej", "Sharwanand"],
        correctIndex: 0,
      },
      {
        id: "ani_m1",
        difficulty: "moderate",
        prompt: "Anirudh's breakout song \"Why This Kolaveri Di\" came from which film?",
        options: ["3", "Ethir Neechal", "Velaiilla Pattadhari", "Kaththi"],
        correctIndex: 0,
      },
      {
        id: "ani_h1",
        difficulty: "hard",
        prompt: "Which 2018 Pawan Kalyan film directed by Trivikram did Anirudh score?",
        options: ["Agnyaathavaasi", "Attarintiki Daredi", "Sardaar Gabbar Singh", "Katamarayudu"],
        correctIndex: 0,
      },
      {
        id: "ani_x1",
        difficulty: "extreme",
        prompt: "Who directed Jersey (2019)?",
        options: ["Gowtam Tinnanuri", "Sekhar Kammula", "Vamshi Paidipally", "Bharat Kamma"],
        correctIndex: 0,
      },
    ],
  },
];

export const TELUGUCINEMALU_PERSONALITIES: TeluguCinemaluPersonality[] = [
  ...heroes,
  ...heroines,
  ...directors,
  ...musicDirectors,
];
