import type { TeluguCinemaluQuestion } from "@shared/types.js";

export const TELUGUCINEMALU_QUESTIONS: TeluguCinemaluQuestion[] = [
  {
    id: "tq_1",
    movieTitle: "Pokiri",
    dialogue: "ఒక్కసారి కమిట్ అయితే నా మాట నేనే వినను!",
    prompt: "Which movie features this iconic Mahesh Babu dialogue?",
    options: ["Pokiri", "Dookudu", "Athadu", "Businessman"],
    correctIndex: 0,
    trivia: "Directed by Puri Jagannadh, Pokiri ran for over 175 days in multiple centers across Andhra Pradesh and Telangana.",
  },
  {
    id: "tq_2",
    movieTitle: "Gabbar Singh",
    dialogue: "నాక్కొంచెం తిక్కుంది, కానీ దానికో లెక్కుంది!",
    prompt: "Which Pawan Kalyan blockbuster has this dialogue?",
    options: ["Gabbar Singh", "Attarintiki Daredi", "Jalsa", "Kushi"],
    correctIndex: 0,
    trivia: "Gabbar Singh was a massive commercial hit that smashed box office records in 2012.",
  },
  {
    id: "tq_3",
    movieTitle: "Baahubali 2: The Conclusion",
    dialogue: "ఎవరు మైహిష్మతి సామ్రాజ్య అధిపతి? అమ్మ నన్ను బలి ఇచ్చినా...",
    prompt: "Which epic film stars Prabhas delivering this dialogue?",
    options: ["Baahubali 2", "RRR", "Magadheera", "Eega"],
    correctIndex: 0,
    trivia: "Directed by S.S. Rajamouli, Baahubali 2 became one of the highest-grossing Indian films worldwide.",
  },
  {
    id: "tq_4",
    movieTitle: "Pushpa: The Rise",
    dialogue: "తగ్గేదే లే!",
    prompt: "Which Allu Arjun blockbuster introduced the slogan 'Thaggedhe Le'?",
    options: ["Pushpa: The Rise", "Ala Vaikunthapurramuloo", "Race Gurram", "Arya"],
    correctIndex: 0,
    trivia: "The hand-under-chin gesture and 'Thaggedhe Le' phrase became a global pop culture sensation.",
  },
  {
    id: "tq_5",
    movieTitle: "Arjun Reddy",
    dialogue: "I am not in the mood to negotiate!",
    prompt: "Which cult hit starring Vijay Deverakonda features this line?",
    options: ["Arjun Reddy", "Geetha Govindam", "Dear Comrade", "Taxiwala"],
    correctIndex: 0,
    trivia: "Arjun Reddy redefined youth cinema in Tollywood with its raw storytelling and soundtrack.",
  },
  {
    id: "tq_6",
    movieTitle: "Indra",
    dialogue: "సింహాసనం మీద కూర్చునే అర్హత...",
    prompt: "Which Chiranjeevi blockbuster features this punch dialogue?",
    options: ["Indra", "Tagore", "Gang Leader", "Gharana Mogudu"],
    correctIndex: 0,
    trivia: "Indra set silver jubilee records in over 122 theaters when released in 2002.",
  },
  {
    id: "tq_7",
    movieTitle: "Magadheera",
    dialogue: "ఒక్కొక్కడ్ని కాదు షేర్ ఖాన్... వంద మందిని ఒకేసారి పంపు!",
    prompt: "Which Ram Charan period action drama contains this 100-man fight dialogue?",
    options: ["Magadheera", "Ranga Sthalam", "RRR", "Nayak"],
    correctIndex: 0,
    trivia: "Magadheera broke all previous Tollywood records and ran for over 1000 days in a theater.",
  },
  {
    id: "tq_8",
    movieTitle: "Athadu",
    dialogue: "నిజం చెప్పకపోవడం అబద్ధం... అబద్ధాన్ని నిజం చేయడం మోసం!",
    prompt: "Which classic Mahesh Babu thriller directed by Trivikram has this dialogue?",
    options: ["Athadu", "Khaleja", "Julayi", "Son of Satyamurthy"],
    correctIndex: 0,
    trivia: "Athadu remains one of the most repeatedly watched movies on Telugu television.",
  },
];
