import type { TeluguCinemaluQuestion } from "@shared/types.js";

export const TELUGUCINEMALU_QUESTIONS: TeluguCinemaluQuestion[] = [
  // ==================== TOLLYWUD (30 Questions) ====================
  {
    id: "tq_t1",
    category: "Tollywood",
    movieTitle: "Pokiri",
    dialogue: "ఒక్కసారి కమిట్ అయితే నా మాట నేనే వినను!",
    prompt: "Which movie features this iconic Mahesh Babu dialogue?",
    options: ["Pokiri", "Dookudu", "Athadu", "Businessman"],
    correctIndex: 0,
    trivia: "Directed by Puri Jagannadh, Pokiri ran for over 175 days in multiple centers across AP and Telangana.",
  },
  {
    id: "tq_t2",
    category: "Tollywood",
    movieTitle: "Gabbar Singh",
    dialogue: "నాక్కొంచెం తిక్కుంది, కానీ దానికో లెక్కుంది!",
    prompt: "Which Pawan Kalyan blockbuster features this famous dialogue?",
    options: ["Gabbar Singh", "Attarintiki Daredi", "Jalsa", "Kushi"],
    correctIndex: 0,
    trivia: "Gabbar Singh was directed by Harish Shankar and broke several box-office records in 2012.",
  },
  {
    id: "tq_t3",
    category: "Tollywood",
    movieTitle: "Baahubali 2: The Conclusion",
    dialogue: "ఎవరు మైహిష్మతి సామ్రాజ్య అధిపతి? అమ్మ నన్ను బలి ఇచ్చినా...",
    prompt: "Which epic film stars Prabhas delivering this powerful line?",
    options: ["Baahubali 2", "RRR", "Magadheera", "Eega"],
    correctIndex: 0,
    trivia: "Directed by S.S. Rajamouli, Baahubali 2 became one of the highest-grossing Indian films worldwide.",
  },
  {
    id: "tq_t4",
    category: "Tollywood",
    movieTitle: "Pushpa: The Rise",
    dialogue: "తగ్గేదే లే!",
    prompt: "Which Allu Arjun blockbuster popularized the iconic slogan 'Thaggedhe Le'?",
    options: ["Pushpa: The Rise", "Ala Vaikunthapurramuloo", "Race Gurram", "Arya"],
    correctIndex: 0,
    trivia: "The beard-rub gesture and 'Thaggedhe Le' phrase became a global pop-culture phenomenon.",
  },
  {
    id: "tq_t5",
    category: "Tollywood",
    movieTitle: "Arjun Reddy",
    dialogue: "I am not in the mood to negotiate!",
    prompt: "Which cult hit starring Vijay Deverakonda features this line?",
    options: ["Arjun Reddy", "Geetha Govindam", "Dear Comrade", "Taxiwala"],
    correctIndex: 0,
    trivia: "Directed by Sandeep Reddy Vanga, Arjun Reddy redefined modern Telugu youth romantic drama.",
  },
  {
    id: "tq_t6",
    category: "Tollywood",
    movieTitle: "Indra",
    dialogue: "సింహాసనం మీద కూర్చునే అర్హత...",
    prompt: "Which Megastar Chiranjeevi blockbuster features this punch dialogue?",
    options: ["Indra", "Tagore", "Gang Leader", "Gharana Mogudu"],
    correctIndex: 0,
    trivia: "Indra set silver-jubilee records in over 122 theaters when released in 2002.",
  },
  {
    id: "tq_t7",
    category: "Tollywood",
    movieTitle: "Magadheera",
    dialogue: "ఒక్కొక్కడ్ని కాదు షేర్ ఖాన్... వంద మందిని ఒకేసారి పంపు!",
    prompt: "Which Ram Charan fantasy-action film contains this 100-man fight sequence dialogue?",
    options: ["Magadheera", "Ranga Sthalam", "RRR", "Nayak"],
    correctIndex: 0,
    trivia: "Magadheera ran for over 1000 days in a theater in Kurnool.",
  },
  {
    id: "tq_t8",
    category: "Tollywood",
    movieTitle: "Athadu",
    dialogue: "నిజం చెప్పకపోవడం అబద్ధం... అబద్ధాన్ని నిజం చేయడం మోసం!",
    prompt: "Which classic Mahesh Babu thriller directed by Trivikram has this dialogue?",
    options: ["Athadu", "Khaleja", "Julayi", "Son of Satyamurthy"],
    correctIndex: 0,
    trivia: "Athadu holds one of the highest television viewership ratings in Tollywood history.",
  },
  {
    id: "tq_t9",
    category: "Tollywood",
    movieTitle: "RRR",
    dialogue: "తొక్కి పడేద్దాం!",
    prompt: "Which Oscar-winning S.S. Rajamouli epic features Jr. NTR and Ram Charan together?",
    options: ["RRR", "Baahubali", "Magadheera", "Yamadonga"],
    correctIndex: 0,
    trivia: "RRR won the Academy Award for Best Original Song for 'Naatu Naatu'.",
  },
  {
    id: "tq_t10",
    category: "Tollywood",
    movieTitle: "Ala Vaikunthapurramuloo",
    dialogue: "మేడమ్ సర్... మేడమ్ అంతే!",
    prompt: "Which Trivikram family entertainer stars Allu Arjun and Pooja Hegde?",
    options: ["Ala Vaikunthapurramuloo", "Race Gurram", "Julayi", "S/O Satyamurthy"],
    correctIndex: 0,
    trivia: "The song 'Butta Bomma' became a mega viral video hit across YouTube.",
  },
  {
    id: "tq_t11",
    category: "Tollywood",
    movieTitle: "Simhadri",
    dialogue: "సింహాద్రి జోలికి వస్తే నరికేస్తా!",
    prompt: "Which blockbuster directed by Rajamouli catapulted Jr. NTR to mass stardom?",
    options: ["Simhadri", "Student No.1", "Yamadonga", "Temper"],
    correctIndex: 0,
    trivia: "Simhadri completed a 175-day run in 55 centers in 2003.",
  },
  {
    id: "tq_t12",
    category: "Tollywood",
    movieTitle: "Rangasthalam",
    dialogue: "నాతో పెట్టుకుంటే రంగాలు రంగాలుగా విరిగిపోతారు!",
    prompt: "Which period drama stars Ram Charan as the hearing-impaired Chitti Babu?",
    options: ["Rangasthalam", "Magadheera", "Dhruva", "Govindudu Andarivadele"],
    correctIndex: 0,
    trivia: "Directed by Sukumar, Rangasthalam received universal critical acclaim for performance & music.",
  },
  {
    id: "tq_t13",
    category: "Tollywood",
    movieTitle: "Eega",
    dialogue: "నన్ను చంపినా నేను మళ్ళీ వస్తా!",
    prompt: "In which Rajamouli film does a murdered man reincarnate as a housefly to take revenge?",
    options: ["Eega", "Maryada Ramanna", "Magadheera", "Vikramarkudu"],
    correctIndex: 0,
    trivia: "Sudeep played the iconic villain in this visual-effects masterpiece.",
  },
  {
    id: "tq_t14",
    category: "Tollywood",
    movieTitle: "Geetha Govindam",
    dialogue: "Inkem Inkem Inkem Kaavaale...",
    prompt: "Which romantic hit starring Vijay Deverakonda and Rashmika Mandanna features this hit song?",
    options: ["Geetha Govindam", "Dear Comrade", "Taxiwala", "Kushi"],
    correctIndex: 0,
    trivia: "The song 'Inkem Inkem' sung by Sid Sriram reached over 500M views.",
  },
  {
    id: "tq_t15",
    category: "Tollywood",
    movieTitle: "Dookudu",
    dialogue: "మైండ్ లో ఫిక్స్ అయితే బ్లైండ్ గా వెళ్ళిపోతా!",
    prompt: "Which action comedy starring Mahesh Babu and Samantha set non-Baahubali records in 2011?",
    options: ["Dookudu", "Pokiri", "Aagadu", "Khaleja"],
    correctIndex: 0,
    trivia: "Directed by Srinu Vaitla, it won seven Nandi Awards.",
  },
  {
    id: "tq_t16",
    category: "Tollywood",
    movieTitle: "Jalsa",
    dialogue: "ఎవడైతే నాకేంటి భాస్కర్!",
    prompt: "Which Pawan Kalyan comedy-action film directed by Trivikram features songs composed by DSP?",
    options: ["Jalsa", "Gabbar Singh", "Attarintiki Daredi", "Kushi"],
    correctIndex: 0,
    trivia: "Jalsa featured a background voice-over by Mahesh Babu.",
  },
  {
    id: "tq_t17",
    category: "Tollywood",
    movieTitle: "Sye",
    dialogue: "ఎవరు గెలిస్తే వాళ్ళదే కాలేజ్ గ్రౌండ్!",
    prompt: "Which Rajamouli film centers around a college Rugby match rivalry?",
    options: ["Sye", "Chatrapathi", "Vikramarkudu", "Student No.1"],
    correctIndex: 0,
    trivia: "Sye introduced Rugby sport drama to South Indian mainstream cinema.",
  },
  {
    id: "tq_t18",
    category: "Tollywood",
    movieTitle: "Chatrapathi",
    dialogue: "ఒక్క అడుగు కూడా వెనక్కి వేయను!",
    prompt: "Which Prabhas action film directed by Rajamouli features the iconic 'Agni Skalana' theme?",
    options: ["Chatrapathi", "Mirchi", "Baahubali", "Darling"],
    correctIndex: 0,
    trivia: "The interval sequence of Chatrapathi remains one of Telugu cinema's most famous scenes.",
  },
  {
    id: "tq_t19",
    category: "Tollywood",
    movieTitle: "Mirchi",
    dialogue: "కట్ చేస్తే కత్తి... నవ్వితే నేస్తం!",
    prompt: "Which Prabhas blockbuster marked the directorial debut of Koratala Siva?",
    options: ["Mirchi", "Srimanthudu", "Janatha Garage", "Bharat Ane Nenu"],
    correctIndex: 0,
    trivia: "Mirchi won six Nandi Awards including Best Feature Film.",
  },
  {
    id: "tq_t20",
    category: "Tollywood",
    movieTitle: "Srimanthudu",
    dialogue: "సంపాదించడం మాత్రమే కాదు... ఊరికి తిరిగి ఇవ్వడం కూడా నేర్చుకోవాలి!",
    prompt: "Which Mahesh Babu social drama highlights village adoption?",
    options: ["Srimanthudu", "Maharshi", "Bharat Ane Nenu", "Sarileru Neekevvaru"],
    correctIndex: 0,
    trivia: "The movie inspired several real-life celebrities to adopt rural villages in Andhra and Telangana.",
  },
  {
    id: "tq_t21",
    category: "Tollywood",
    movieTitle: "Kushi",
    dialogue: "అబ్బాయి... ఎంత బాగుందో!",
    prompt: "Which 2001 romantic cult hit starring Pawan Kalyan and Bhumika Chawla became a sensational blockbuster?",
    options: ["Kushi", "Badri", "Tholi Prema", "Gopala Gopala"],
    correctIndex: 0,
    trivia: "Directed by S.J. Suryah, its music by Mani Sharma was a chartbuster.",
  },
  {
    id: "tq_t22",
    category: "Tollywood",
    movieTitle: "Vikramarkudu",
    dialogue: "జింతాత జిత జిత!",
    prompt: "Which Ravi Teja double-role blockbuster featured the cop Vikram Rathore?",
    options: ["Vikramarkudu", "Kick", "Venky", "Krack"],
    correctIndex: 0,
    trivia: "It was remade into Hindi as Rowdy Rathore and Tamil as Siruthai.",
  },
  {
    id: "tq_t23",
    category: "Tollywood",
    movieTitle: "Kick",
    dialogue: "నేను ఏది చేసినా ఒక కిక్ కోసం చేస్తా!",
    prompt: "Which action comedy starring Ravi Teja and Ileana D'Cruz is all about seeking a 'kick' in life?",
    options: ["Kick", "Venky", "Dubai Seenu", "Mirapakay"],
    correctIndex: 0,
    trivia: "Kick was directed by Surender Reddy and scored by Thaman S.",
  },
  {
    id: "tq_t24",
    category: "Tollywood",
    movieTitle: "Jersey",
    dialogue: "ఎప్పటికైనా నన్ను నిన్ను గర్వంగా చూసుకోవాలి నాన్నా!",
    prompt: "Which emotional sports drama stars Nani as late-bloomer cricketer Arjun?",
    options: ["Jersey", "Shyam Singha Roy", "Majili", "Bhale Bhale Magadivoy"],
    correctIndex: 0,
    trivia: "Jersey won two National Film Awards including Best Feature Film in Telugu.",
  },
  {
    id: "tq_t25",
    category: "Tollywood",
    movieTitle: "Mahanati",
    dialogue: "నటిగా నేనేంటి అనేది ప్రపంచానికి తెలుసు...",
    prompt: "Which biographical film starring Keerthy Suresh is based on legendary actress Savitri?",
    options: ["Mahanati", "NTR Kathanayakudu", "Devadasu", "Missamma"],
    correctIndex: 0,
    trivia: "Keerthy Suresh received the National Film Award for Best Actress for her performance.",
  },
  {
    id: "tq_t26",
    category: "Tollywood",
    movieTitle: "Sita Ramam",
    dialogue: "సీతారాముల కథ ఇది... ఎప్పటికీ అమరం!",
    prompt: "Which romantic period drama stars Dulquer Salmaan and Mrunal Thakur?",
    options: ["Sita Ramam", "Mahanati", "Kanche", "Radhe Shyam"],
    correctIndex: 0,
    trivia: "Directed by Hanu Raghavapudi, the film was acclaimed for its cinematography and soundtrack.",
  },
  {
    id: "tq_t27",
    category: "Tollywood",
    movieTitle: "HanuMan",
    dialogue: "అంజనాద్రికి ఆపద వస్తే శంబాలుడే కాదు... ఆ ఆంజనేయుడే దిగివస్తాడు!",
    prompt: "Which 2024 superhero film directed by Prasanth Varma stars Teja Sajja?",
    options: ["HanuMan", "Karthikeya 2", "Bimbisara", "Akhanda"],
    correctIndex: 0,
    trivia: "HanuMan became the highest-grossing Telugu film of 2024 worldwide.",
  },
  {
    id: "tq_t28",
    category: "Tollywood",
    movieTitle: "Karthikeya 2",
    dialogue: "శ్రీకృష్ణుడి జ్ఞానం ప్రపంచానికి అత్యంత అవసరం!",
    prompt: "Which mystery thriller starring Nikhil Siddhartha revolves around Lord Krishna's anklet?",
    options: ["Karthikeya 2", "Karthikeya", "Bimbisara", "Mystery"],
    correctIndex: 0,
    trivia: "Karthikeya 2 won the National Film Award for Best Feature Film in Telugu.",
  },
  {
    id: "tq_t29",
    category: "Tollywood",
    movieTitle: "Akhanda",
    dialogue: "ఒక్కసారి మాటకు కట్టుబడితే ప్రాణమైనా ఇస్తా!",
    prompt: "Which action drama starring Nandamuri Balakrishna directed by Boyapati Srinu features the Aghora character?",
    options: ["Akhanda", "Legend", "Simha", "Veera Simha Reddy"],
    correctIndex: 0,
    trivia: "Thaman's roaring background score for Akhanda received immense audience appreciation.",
  },
  {
    id: "tq_t30",
    category: "Tollywood",
    movieTitle: "Manam",
    dialogue: "ప్రేమ ఎప్పటికీ చనిపోదు... మళ్ళీ జన్మిస్తుంది!",
    prompt: "Which classic fantasy movie features three generations of the Akkineni family (ANR, Nagarjuna, Naga Chaitanya)?",
    options: ["Manam", "Sogade Chinni Nayana", "Hello", "Bangarraju"],
    correctIndex: 0,
    trivia: "Manam was legendary actor Akkineni Nageswara Rao's final film before his passing.",
  },

  // ==================== KOLLYWOOD (30 Questions) ====================
  {
    id: "tq_k1",
    category: "Kollywood",
    movieTitle: "Baasha",
    dialogue: "நான் ஒரு தடவை சொன்னா... நூறு தடவை சொன்ன மாதிரி!",
    prompt: "Which Superstar Rajinikanth blockbuster features this legendary line ('If I say it once, it's like 100 times')?",
    options: ["Baasha", "Annamalai", "Padayappa", "Kabali"],
    correctIndex: 0,
    trivia: "Baasha directed by Suresh Krissha is considered one of Rajinikanth's definitive action classics.",
  },
  {
    id: "tq_k2",
    category: "Kollywood",
    movieTitle: "Vikram",
    dialogue: "ఆరంభిక్కలామా! (Shall we begin?)",
    prompt: "Which 2022 action extravaganza starring Kamal Haasan and Vijay Sethupathi featured this iconic intro quote?",
    options: ["Vikram", "Kaithi", "Leo", "Master"],
    correctIndex: 0,
    trivia: "Directed by Lokesh Kanagaraj, Vikram is part of the Lokesh Cinematic Universe (LCU).",
  },
  {
    id: "tq_k3",
    category: "Kollywood",
    movieTitle: "Master",
    dialogue: "I am waiting!",
    prompt: "Which Thalapathy Vijay blockbuster features the signature line 'I am waiting'?",
    options: ["Master", "Thuppakki", "Kaththi", "Theri"],
    correctIndex: 0,
    trivia: "Master was directed by Lokesh Kanagaraj with music by Anirudh Ravichander.",
  },
  {
    id: "tq_k4",
    category: "Kollywood",
    movieTitle: "Jailer",
    dialogue: "Hukum... Tiger Ka Hukum!",
    prompt: "Which Rajinikanth 2023 blockbuster contains the viral chartbuster 'Hukum'?",
    options: ["Jailer", "Petta", "Darbar", "Kaala"],
    correctIndex: 0,
    trivia: "Jailer directed by Nelson Dilipkumar grossed over 600 crore worldwide.",
  },
  {
    id: "tq_k5",
    category: "Kollywood",
    movieTitle: "Mankatha",
    dialogue: "Money, Money, Money!",
    prompt: "Which heist action thriller starring Ajith Kumar marked his 50th film?",
    options: ["Mankatha", "Veeram", "Vedalam", "Viswasam"],
    correctIndex: 0,
    trivia: "Directed by Venkat Prabhu, Mankatha was a major box office success.",
  },
  {
    id: "tq_k6",
    category: "Kollywood",
    movieTitle: "Ponniyin Selvan",
    dialogue: "చోళ సామ్రాజ్యానికి విజయీభవ!",
    prompt: "Which Mani Ratnam historical epic is based on Kalki Krishnamurthy's novel?",
    options: ["Ponniyin Selvan", "Kaatru Veliyidai", "Raavanan", "Bombay"],
    correctIndex: 0,
    trivia: "The two-part epic stars Vikram, Karthi, Jayam Ravi, Aishwarya Rai, and Trisha.",
  },
  {
    id: "tq_k7",
    category: "Kollywood",
    movieTitle: "Kaithi",
    dialogue: "లారీ డ్రైవర్ ఢిల్లీ ఆట చూడు!",
    prompt: "Which night-spanning action thriller starring Karthi was the foundation of the LCU universe?",
    options: ["Kaithi", "Theeran Adhigaaram Ondru", "Vikram", "Leo"],
    correctIndex: 0,
    trivia: "Kaithi features no female lead or songs, focusing purely on high-octane plot pacing.",
  },
  {
    id: "tq_k8",
    category: "Kollywood",
    movieTitle: "Enthiran (Robot)",
    dialogue: "Black Sheep... 1, 2, 3!",
    prompt: "Which Sci-Fi spectacle starred Rajinikanth as Scientist Vaseegaran and Chitti the Robot?",
    options: ["Enthiran", "2.0", "Kochadaiiyaan", "Sivaji"],
    correctIndex: 0,
    trivia: "Directed by Shankar, Enthiran featured revolutionary visual effects and AR Rahman's music.",
  },
  {
    id: "tq_k9",
    category: "Kollywood",
    movieTitle: "Sivaji: The Boss",
    dialogue: "సింగం సింగిల్‌గానే వస్తుంది!",
    prompt: "Which Rajinikanth action blockbuster directed by Shankar popularized 'Cool Boss' style?",
    options: ["Sivaji", "Anniyan", "Chandramukhi", "Lingaa"],
    correctIndex: 0,
    trivia: "Sivaji was the first Indian film to incorporate Dolby Atmos surround sound technology.",
  },
  {
    id: "tq_k10",
    category: "Kollywood",
    movieTitle: "Anniyan (Aparichithudu)",
    dialogue: "తప్పు చేసినవాడు శిక్ష అనుభవించాల్సిందే!",
    prompt: "Which Shankar psychological thriller stars Vikram in a triple role (Ramanujam, Remo, Anniyan)?",
    options: ["Anniyan", "I", "Saamy", "Pithamagan"],
    correctIndex: 0,
    trivia: "Vikram won the Filmfare Award for Best Actor – Tamil for his performance.",
  },
  {
    id: "tq_k11",
    category: "Kollywood",
    movieTitle: "Ghajini",
    dialogue: "15 నిమిషాల జ్ఞాపకశక్తి మాత్రమే ఉంటుంది!",
    prompt: "Which Suriya action thriller features a protagonist suffering from short-term memory loss?",
    options: ["Ghajini", "Singham", "7 Aum Arivu", "24"],
    correctIndex: 0,
    trivia: "Directed by A.R. Murugadoss, Ghajini was later remade in Hindi starring Aamir Khan.",
  },
  {
    id: "tq_k12",
    category: "Kollywood",
    movieTitle: "Singam",
    dialogue: "ఓంగారాన్ని వింటే సింగం వేటాడటం ఖాయం!",
    prompt: "Which Suriya cop franchise directed by Hari spawned three blockbuster installments?",
    options: ["Singam", "Saamy", "Ayan", "Kaakha Kaakha"],
    correctIndex: 0,
    trivia: "Singam was remade into Hindi starring Ajay Devgn and Telugu as Yamudu.",
  },
  {
    id: "tq_k13",
    category: "Kollywood",
    movieTitle: "96",
    dialogue: "రామ్... జానూ!",
    prompt: "Which romantic nostalgia drama stars Vijay Sethupathi and Trisha as high-school sweethearts meeting at a reunion?",
    options: ["96", "Master", "Vikram Vedha", "Naanum Rowdy Dhaan"],
    correctIndex: 0,
    trivia: "The soundtrack composed by Govind Vasantha achieved cult status across India.",
  },
  {
    id: "tq_k14",
    category: "Kollywood",
    movieTitle: "Vikram Vedha",
    dialogue: "ఒక కథ చెప్తా విను!",
    prompt: "Which neo-noir thriller features Madhavan as cop Vikram and Vijay Sethupathi as gangster Vedha?",
    options: ["Vikram Vedha", "Pizza", "Master", "Soodhu Kavvum"],
    correctIndex: 0,
    trivia: "The story is inspired by the ancient Indian folklore of Baital Pachisi (Vikram and Betaal).",
  },
  {
    id: "tq_k15",
    category: "Kollywood",
    movieTitle: "Jai Bhim",
    dialogue: "న్యాయం లభించేవరకు పోరాడతాం!",
    prompt: "Which legal drama starring Suriya as Advocate Chandru won international acclaim on Prime Video?",
    options: ["Jai Bhim", "Soorarai Pottru", "Ghajini", "Singam"],
    correctIndex: 0,
    trivia: "Jai Bhim briefly held the top user rating for a movie on IMDb.",
  },
  {
    id: "tq_k16",
    category: "Kollywood",
    movieTitle: "Soorarai Pottru (Aakaasam Nee Haddhu Ra)",
    dialogue: "ఆకాశమే నీ హద్దు రా!",
    prompt: "Which National-Award winning drama stars Suriya as low-cost airline founder Maara?",
    options: ["Soorarai Pottru", "Jai Bhim", "24", "7 Aum Arivu"],
    correctIndex: 0,
    trivia: "Suriya won the National Film Award for Best Actor for his role.",
  },
  {
    id: "tq_k17",
    category: "Kollywood",
    movieTitle: "Theri",
    dialogue: "విజయ్‌కుమార్ ఐపీఎస్!",
    prompt: "Which Atlee action drama stars Vijay as a baker hiding a past life as an honest police officer?",
    options: ["Theri", "Mersal", "Bigil", "Jawan"],
    correctIndex: 0,
    trivia: "Theri was Atlee's first collaboration with Vijay.",
  },
  {
    id: "tq_k18",
    category: "Kollywood",
    movieTitle: "Mersal",
    dialogue: "వైద్యం అందరికీ ఉచితంగా అందాలి!",
    prompt: "Which Vijay triple-role action film directed by Atlee revolves around medical corruption?",
    options: ["Mersal", "Theri", "Bigil", "Kaththi"],
    correctIndex: 0,
    trivia: "Mersal featured music composed by A.R. Rahman.",
  },
  {
    id: "tq_k19",
    category: "Kollywood",
    movieTitle: "Thuppakki",
    dialogue: "I am waiting!",
    prompt: "Which A.R. Murugadoss spy thriller stars Vijay as Jagadish IPS hunting sleeper cells in Mumbai?",
    options: ["Thuppakki", "Kaththi", "Sarkar", "Holiday"],
    correctIndex: 0,
    trivia: "Thuppakki was the first Tamil film to cross the 100 crore mark in 2012.",
  },
  {
    id: "tq_k20",
    category: "Kollywood",
    movieTitle: "Vada Chennai",
    dialogue: "ఇది మా నేల... మా జనాలు!",
    prompt: "Which acclaimed gangster epic directed by Vetrimaaran stars Dhanush as Anbu?",
    options: ["Vada Chennai", "Asuran", "Karnan", "Pudhupettai"],
    correctIndex: 0,
    trivia: "Vada Chennai received high praise for its realistic narrative and world-building.",
  },
  {
    id: "tq_k21",
    category: "Kollywood",
    movieTitle: "Asuran",
    dialogue: "చదువు ఒక్కటే నిన్ను ఎవరూ లాక్కోలేని ఆస్తి!",
    prompt: "Which Vetrimaaran rural action drama starring Dhanush won two National Film Awards?",
    options: ["Asuran", "Karnan", "Vada Chennai", "Raanjhanaa"],
    correctIndex: 0,
    trivia: "Dhanush won the Best Actor National Award for his portrayal of Sivasaami.",
  },
  {
    id: "tq_k22",
    category: "Kollywood",
    movieTitle: "Pariyerum Perumal",
    dialogue: "మాకూ సమాన హక్కులు ఉన్నాయి!",
    prompt: "Which anti-caste drama film produced by Pa. Ranjith received critical acclaim in 2018?",
    options: ["Pariyerum Perumal", "Karnan", "Maamannan", "Sarpatta Parambarai"],
    correctIndex: 0,
    trivia: "Directed by Mari Selvaraj, it won the Filmfare Award for Best Film – Tamil.",
  },
  {
    id: "tq_k23",
    category: "Kollywood",
    movieTitle: "Sarpatta Parambarai",
    dialogue: "బాక్సింగ్ రింగ్ లో నీ ఆవేశం చూపించు!",
    prompt: "Which period sports drama starring Arya as Kabilan revolves around boxing clans in North Madras?",
    options: ["Sarpatta Parambarai", "Pariyerum Perumal", "Karnan", "Vada Chennai"],
    correctIndex: 0,
    trivia: "Directed by Pa. Ranjith, Arya underwent intense physical training to portray the boxer.",
  },
  {
    id: "tq_k24",
    category: "Kollywood",
    movieTitle: "Chandramukhi",
    dialogue: "లకలకలకలక!",
    prompt: "Which horror-comedy starring Rajinikanth and Jyothika ran for 890 days at Shanthi Theatre?",
    options: ["Chandramukhi", "Anniyan", "Padayappa", "Muthu"],
    correctIndex: 0,
    trivia: "Rajinikanth's 'Laka Laka' laugh became an iconic pop-culture catchphrase.",
  },
  {
    id: "tq_k25",
    category: "Kollywood",
    movieTitle: "Padayappa",
    dialogue: "నా వయసైనా నా గ్లామర్ తగ్గదు!",
    prompt: "Which Rajinikanth blockbuster featured Ramya Krishnan in her career-best role as Neelambari?",
    options: ["Padayappa", "Baasha", "Annamalai", "Muthu"],
    correctIndex: 0,
    trivia: "Neelambari is celebrated as one of Indian cinema's greatest antagonists.",
  },
  {
    id: "tq_k26",
    category: "Kollywood",
    movieTitle: "Indian (Bharateeyudu)",
    dialogue: "లంచగొండితనాన్ని సహించేది లేదు!",
    prompt: "Which Shankar vigilante film stars Kamal Haasan as the elderly freedom fighter Senapathy?",
    options: ["Indian", "Anniyan", "Nayakan", "Dasavathaaram"],
    correctIndex: 0,
    trivia: "Kamal Haasan won the National Film Award for Best Actor for his role.",
  },
  {
    id: "tq_k27",
    category: "Kollywood",
    movieTitle: "Nayakan",
    dialogue: "నాన్ అడిచ్చా నీ సెత్తురువ!",
    prompt: "Which Mani Ratnam crime masterpiece starring Kamal Haasan was listed in Time Magazine's All-Time 100 Movies?",
    options: ["Nayakan", "Thalapathi", "Indian", "Bombay"],
    correctIndex: 0,
    trivia: "The film was loosely based on the life of Bombay underworld don Varadarajan Mudaliar.",
  },
  {
    id: "tq_k28",
    category: "Kollywood",
    movieTitle: "Thalapathi",
    dialogue: "సూర్యా... నా స్నేహితుడు!",
    prompt: "Which Mani Ratnam classic based on Mahabharata's Karna-Duryodhana friendship stars Rajinikanth and Mammootty?",
    options: ["Thalapathi", "Nayakan", "Baasha", "Roja"],
    correctIndex: 0,
    trivia: "Ilaiyaraaja's music for Thalapathi was rated among top soundtracks worldwide.",
  },
  {
    id: "tq_k29",
    category: "Kollywood",
    movieTitle: "Love Today",
    dialogue: "ఒక్క రోజు ఫోన్ ఎక్స్చేంజ్ చేసుకుందాం!",
    prompt: "Which 2022 romantic comedy directed by Pradeep Ranganathan centers around swapping smartphones before marriage?",
    options: ["Love Today", "Dragon", "Comali", "Don"],
    correctIndex: 0,
    trivia: "Love Today became one of the biggest sleeper hits in Tamil box-office history.",
  },
  {
    id: "tq_k30",
    category: "Kollywood",
    movieTitle: "Leo",
    dialogue: "Bloody Sweet!",
    prompt: "Which Vijay and Lokesh Kanagaraj thriller brought Leo Das into the LCU universe?",
    options: ["Leo", "Master", "Vikram", "Kaithi"],
    correctIndex: 0,
    trivia: "Leo grossed over 600 crore worldwide becoming Vijay's highest grossing film.",
  },

  // ==================== SANDALWOOD (30 Questions) ====================
  {
    id: "tq_s1",
    category: "Sandalwood",
    movieTitle: "K.G.F: Chapter 1",
    dialogue: "Violence... Violence... Violence! I don't like it, I avoid! But violence likes me!",
    prompt: "Which Sandalwood masterpiece starring Yash as Rocky Bhai became a pan-India revolution?",
    options: ["K.G.F: Chapter 1", "Kantara", "Ugramm", "Salaga"],
    correctIndex: 0,
    trivia: "Directed by Prashanth Neel, KGF 1 was the first Kannada film to cross 250 crore.",
  },
  {
    id: "tq_s2",
    category: "Sandalwood",
    movieTitle: "K.G.F: Chapter 2",
    dialogue: "గ్యాంగ్ తో వచ్చేవాడు గ్యాంగ్‌స్టర్... ఒక్కడే వచ్చేవాడు మాన్స్టర్!",
    prompt: "Which film starring Yash broke opening day box-office records across India in 2022?",
    options: ["K.G.F: Chapter 2", "Kantara", "Vikrant Rona", "Kabzaa"],
    correctIndex: 0,
    trivia: "K.G.F: Chapter 2 grossed over 1200 crore worldwide.",
  },
  {
    id: "tq_s3",
    category: "Sandalwood",
    movieTitle: "Kantara",
    dialogue: "వరాహరూపం... దైవ నర్తన!",
    prompt: "Which Rishab Shetty folk-mythological masterpiece features the divine Bhoota Kola ritual?",
    options: ["Kantara", "K.G.F", "Kirik Party", "Bell Bottom"],
    correctIndex: 0,
    trivia: "Rishab Shetty directed, wrote, and played the lead role in Kantara.",
  },
  {
    id: "tq_s4",
    category: "Sandalwood",
    movieTitle: "777 Charlie",
    dialogue: "కుక్క ప్రేమ మాత్రమే నిస్వార్థమైనది!",
    prompt: "Which emotional adventure film stars Rakshit Shetty and a Labrador dog named Charlie?",
    options: ["777 Charlie", "Kirik Party", "Avane Srimannarayana", "Ulidavaru Kandanthe"],
    correctIndex: 0,
    trivia: "777 Charlie won the National Film Award for Best Feature Film in Kannada.",
  },
  {
    id: "tq_s5",
    category: "Sandalwood",
    movieTitle: "Rajakumara",
    dialogue: "అభిమానుల గుండెల్లో రాజకుమారుడు!",
    prompt: "Which Puneeth Rajkumar blockbuster directed by Santhosh Ananddram set record collections in 2017?",
    options: ["Rajakumara", "Appu", "Raaj", "James"],
    correctIndex: 0,
    trivia: "The song 'Neene Rama Neene Shama' became an emotional anthem across Karnataka.",
  },
  {
    id: "tq_s6",
    category: "Sandalwood",
    movieTitle: "Vikrant Rona",
    dialogue: "దయ్యాల అడవిలోకి స్వాగతం!",
    prompt: "Which 3D action thriller starred Kiccha Sudeep as Inspector Vikrant Rona?",
    options: ["Vikrant Rona", "Kotigobba 3", "Pailwaan", "Villain"],
    correctIndex: 0,
    trivia: "The film featured Jacqueline Fernandez in the hit song 'Ra Ra Rakkamma'.",
  },
  {
    id: "tq_s7",
    category: "Sandalwood",
    movieTitle: "Kirik Party",
    dialogue: "కాలేజ్ రోజులు ఎప్పటికీ తిరిగిరావు!",
    prompt: "Which college campus comedy film directed by Rishab Shetty starred Rakshit Shetty and Rashmika Mandanna?",
    options: ["Kirik Party", "777 Charlie", "Kantara", "Bell Bottom"],
    correctIndex: 0,
    trivia: "Kirik Party ran for over 150 days in theaters and launched Rashmika Mandanna's career.",
  },
  {
    id: "tq_s8",
    category: "Sandalwood",
    movieTitle: "Ugramm",
    dialogue: "ఈ ఏరియాకి నేనే రాజు!",
    prompt: "Which debut film of Prashanth Neel starring Sriimurali established Neel's dark-tone action aesthetic?",
    options: ["Ugramm", "K.G.F", "Mufti", "Rathaavara"],
    correctIndex: 0,
    trivia: "Prashanth Neel was praised for bringing Hollywood-style gritty cinematography to Kannada cinema.",
  },
  {
    id: "tq_s9",
    category: "Sandalwood",
    movieTitle: "Mufti",
    dialogue: "నల్ల చొక్కా తొడిగిన భైరవ!",
    prompt: "Which neo-noir action film stars Shiva Rajkumar as crime lord Bhairathi Ranagal?",
    options: ["Mufti", "Tagaru", "Shivalinga", "Bhajarangi"],
    correctIndex: 0,
    trivia: "Mufti was remade in Tamil as Pathu Thala starring Silambarasan TR.",
  },
  {
    id: "tq_s10",
    category: "Sandalwood",
    movieTitle: "Tagaru",
    dialogue: "పోలీస్ ఐజీ శివకుమార్ దెబ్బ!",
    prompt: "Which non-linear crime action film stars Shiva Rajkumar and Dhananjaya as 'Daali'?",
    options: ["Tagaru", "Mufti", "Salaga", "Head Bush"],
    correctIndex: 0,
    trivia: "Dhananjaya's villain character 'Daali' became so popular that it spawned a spinoff movie.",
  },
  {
    id: "tq_s11",
    category: "Sandalwood",
    movieTitle: "Lucia",
    dialogue: "కలలు నిజమవుతాయి... జాగ్రత్త!",
    prompt: "Which crowd-funded psychological thriller directed by Pawan Kumar gained global festival acclaim?",
    options: ["Lucia", "U-Turn", "Super", "Psychology"],
    correctIndex: 0,
    trivia: "Lucia was the first crowd-funded film in Kannada cinema history.",
  },
  {
    id: "tq_s12",
    category: "Sandalwood",
    movieTitle: "U-Turn",
    dialogue: "ఫ్లైఓవర్ మీద డివైడర్ జరపకండి!",
    prompt: "Which mystery horror-thriller starring Shraddha Srinath revolves around accidents on a flyover?",
    options: ["U-Turn", "Lucia", "Kavaludaari", "Diya"],
    correctIndex: 0,
    trivia: "Directed by Pawan Kumar, U-Turn was remade in Telugu/Tamil starring Samantha.",
  },
  {
    id: "tq_s13",
    category: "Sandalwood",
    movieTitle: "Mungaru Male",
    dialogue: "తుంపరల వర్షంలో ప్రేమ పయనము!",
    prompt: "Which 2006 romantic classic starring Ganesh and Pooja Gandhi ran for over 865 days?",
    options: ["Mungaru Male", "Gaalipata", "Cheluvina Chittara", "Taj Mahal"],
    correctIndex: 0,
    trivia: "Mungaru Male holds the record for the longest-running film in a multiplex in India.",
  },
  {
    id: "tq_s14",
    category: "Sandalwood",
    movieTitle: "Gaalipata",
    dialogue: "ముగ్గురు మిత్రులు... ఒకే గాలిపటం!",
    prompt: "Which Yogaraj Bhat romantic comedy starring Ganesh, Anant Nag, and Diganth became a huge musical hit?",
    options: ["Gaalipata", "Mungaru Male", "Pancharangi", "Paramathma"],
    correctIndex: 0,
    trivia: "The songs composed by V. Harikrishna were top chartbusters across South India.",
  },
  {
    id: "tq_s15",
    category: "Sandalwood",
    movieTitle: "Appu",
    dialogue: "నాతో ఆటలాడొద్దు!",
    prompt: "Which 2002 debut blockbuster launched Puneeth Rajkumar as a solo lead actor?",
    options: ["Appu", "Abhi", "Veera Kannadiga", "Maurya"],
    correctIndex: 0,
    trivia: "Appu ran for over 200 days and was remade in Telugu as Idiot starring Ravi Teja.",
  },
  {
    id: "tq_s16",
    category: "Sandalwood",
    movieTitle: "Jackie",
    dialogue: "జాకీ ఎంట్రీ ఇస్తే బొమ్మ హిట్!",
    prompt: "Which Puneeth Rajkumar mass action drama directed by Duniya Soori scored huge box-office numbers in 2010?",
    options: ["Jackie", "Anna Bond", "Hudugaru", "Rana Vikrama"],
    correctIndex: 0,
    trivia: "Jackie was praised for its action choreography and V. Harikrishna's music.",
  },
  {
    id: "tq_s17",
    category: "Sandalwood",
    movieTitle: "Sanju Weds Geetha",
    dialogue: "గీత కోసమే సంజు జీవితం!",
    prompt: "Which tragic romance starring Srinagara Kitty and Ramya won major awards in 2011?",
    options: ["Sanju Weds Geetha", "Inti Ninna Preeti", "Johny Mera Naam", "Love Guru"],
    correctIndex: 0,
    trivia: "Jassie Gift's music for the film was acclaimed across Karnataka.",
  },
  {
    id: "tq_s18",
    category: "Sandalwood",
    movieTitle: "Kavaludaari",
    dialogue: "పాత కేసుల వెనుక రహస్యం!",
    prompt: "Which Hemanth Rao neo-noir investigative thriller starred Rishi and Anant Nag as crime solvers?",
    options: ["Kavaludaari", "Godhi Banna Sadharana Mykattu", "Sapta Sagaradaache Ello", "Birbal"],
    correctIndex: 0,
    trivia: "Kavaludaari was produced by Puneeth Rajkumar's PRK Productions.",
  },
  {
    id: "tq_s19",
    category: "Sandalwood",
    movieTitle: "Godhi Banna Sadharana Mykattu",
    dialogue: "జ్ఞాపకాలు చెరిగిపోయినా ప్రేమ చెరగదు!",
    prompt: "Which emotional drama starring Anant Nag as an Alzheimer's patient won international praise?",
    options: ["Godhi Banna Sadharana Mykattu", "Kavaludaari", "Sapta Sagaradaache Ello", "Dia"],
    correctIndex: 0,
    trivia: "Anant Nag's sensitive performance as Venkoba Rao won widespread critical acclaim.",
  },
  {
    id: "tq_s20",
    category: "Sandalwood",
    movieTitle: "Sapta Sagaradaache Ello (Side A & B)",
    dialogue: "ఏడు సముద్రాల అవతల మన కలలు!",
    prompt: "Which romantic drama two-part saga directed by Hemanth M. Rao stars Rakshit Shetty and Rukmini Vasanth?",
    options: ["Sapta Sagaradaache Ello", "777 Charlie", "Ulidavaru Kandanthe", "Kirik Party"],
    correctIndex: 0,
    trivia: "The film was lauded for its poetic tone, score, and emotional depth.",
  },
  {
    id: "tq_s21",
    category: "Sandalwood",
    movieTitle: "Ulidavaru Kandanthe",
    dialogue: "ఒకే నిజం... వేర్వేరు కోణాలు!",
    prompt: "Which neo-noir anthology thriller directed by Rakshit Shetty introduced the character 'Richie'?",
    options: ["Ulidavaru Kandanthe", "Kirik Party", "777 Charlie", "Avane Srimannarayana"],
    correctIndex: 0,
    trivia: "The film was remade in Tamil as Richie starring Nivin Pauly.",
  },
  {
    id: "tq_s22",
    category: "Sandalwood",
    movieTitle: "Avane Srimannarayana",
    dialogue: "అమరావతి ఖజానా నాదే!",
    prompt: "Which fantasy Western-comedy starring Rakshit Shetty features a quirky cop hunting lost treasure?",
    options: ["Avane Srimannarayana", "Ulidavaru Kandanthe", "777 Charlie", "Bell Bottom"],
    correctIndex: 0,
    trivia: "The film spent over three years in scriptwriting and post-production.",
  },
  {
    id: "tq_s23",
    category: "Sandalwood",
    movieTitle: "Bell Bottom",
    dialogue: "డిటెక్టివ్ దివాకర ఆట షురూ!",
    prompt: "Which 1980s retro detective comedy starring Rishab Shetty as Detective Diwakara became a box office sleeper hit?",
    options: ["Bell Bottom", "Kantara", "Kirik Party", "Hero"],
    correctIndex: 0,
    trivia: "Bell Bottom was one of the highest-grossing Kannada films of 2019.",
  },
  {
    id: "tq_s24",
    category: "Sandalwood",
    movieTitle: "Dia",
    dialogue: "ప్రేమను వ్యక్తపరచడంలో ఆలస్యం చేయకు!",
    prompt: "Which emotional romantic tragedy directed by K. S. Ashoka became a massive OTT hit during lockdown?",
    options: ["Dia", "Love Mocktail", "Krishna Talkies", "RangiTaranga"],
    correctIndex: 0,
    trivia: "Dia's unexpected climax left audiences deeply emotional and talking for months.",
  },
  {
    id: "tq_s25",
    category: "Sandalwood",
    movieTitle: "Love Mocktail",
    dialogue: "జీవితం ఒక మోక్టైల్ లాంటిది!",
    prompt: "Which romantic drama directed by and starring Darling Krishna gained cult status via word of mouth?",
    options: ["Love Mocktail", "Dia", "Gaalipata", "Mungaru Male"],
    correctIndex: 0,
    trivia: "Darling Krishna and Milana Nagaraj's chemistry led to a successful sequel.",
  },
  {
    id: "tq_s26",
    category: "Sandalwood",
    movieTitle: "RangiTaranga",
    dialogue: "కమరొట్టు అనే గ్రామంలో దాగివున్న రహస్యం!",
    prompt: "Which mystery thriller directed by Anup Bhandari became the first Kannada film to enter US box-office charts?",
    options: ["RangiTaranga", "Vikrant Rona", "Kavaludaari", "U-Turn"],
    correctIndex: 0,
    trivia: "RangiTaranga was shortlisted for the 88th Academy Awards official selection list.",
  },
  {
    id: "tq_s27",
    category: "Sandalwood",
    movieTitle: "Bangarada Manushya",
    dialogue: "భూమియే మన తల్లి... వ్యవసాయమే మన జీవనం!",
    prompt: "Which legendary Dr. Rajkumar film ran for over two years at the States Theatre in Bengaluru?",
    options: ["Bangarada Manushya", "Kasturi Nivasa", "Babruvahana", "Anantana Avantara"],
    correctIndex: 0,
    trivia: "The film inspired thousands of educated youths to return to rural Karnataka for farming.",
  },
  {
    id: "tq_s28",
    category: "Sandalwood",
    movieTitle: "Kasturi Nivasa",
    dialogue: "దానం చేయడంలో ఆనందం ఉంది!",
    prompt: "Which classic drama starring Dr. Rajkumar as generous industrialist Chandrashekar is an all-time classic?",
    options: ["Kasturi Nivasa", "Bangarada Manushya", "Mayura", "Satya Harishchandra"],
    correctIndex: 0,
    trivia: "Kasturi Nivasa was re-released in color in 2014 to enthusiastic crowds.",
  },
  {
    id: "tq_s29",
    category: "Sandalwood",
    movieTitle: "Om",
    dialogue: "సత్య అనే రౌడీ మార్గం బ్లేడ్ తో రాసింది!",
    prompt: "Which cult crime film directed by Upendra starring Shiva Rajkumar featured real underworld dons in cast?",
    options: ["Om", "A", "Upendra", "Super"],
    correctIndex: 0,
    trivia: "Om was re-released over 550 times in theaters across Karnataka.",
  },
  {
    id: "tq_s30",
    category: "Sandalwood",
    movieTitle: "Upendra (Uppi)",
    dialogue: "నేను... నా రక్తం... నా స్వార్థం!",
    prompt: "Which psychological film directed by and starring Upendra explored ego and self-love?",
    options: ["Upendra", "A", "Super", "Hollywood"],
    correctIndex: 0,
    trivia: "Upendra's unconventional narrative techniques revolutionized Kannada filmmaking in the late 90s.",
  },

  // ==================== BOLLYWOOD (30 Questions) ====================
  {
    id: "tq_b1",
    category: "Bollywood",
    movieTitle: "Sholay",
    dialogue: "Kitne aadmi the?",
    prompt: "Which iconic villain Amjad Khan (Gabbar Singh) asked this famous question in Sholay?",
    options: ["Gabbar Singh", "Mogambo", "Kancha Cheena", "Shakaal"],
    correctIndex: 0,
    trivia: "Sholay ran continuously for over five years at Minerva Theatre in Mumbai.",
  },
  {
    id: "tq_b2",
    category: "Bollywood",
    movieTitle: "Dilwale Dulhania Le Jayenge",
    dialogue: "Bade bade deshon mein aisi chhoti chhoti baatein hoti rehti hain, Senorita!",
    prompt: "Which Shah Rukh Khan and Kajol romantic blockbuster contains this famous quote?",
    options: ["Dilwale Dulhania Le Jayenge", "Kuch Kuch Hota Hai", "Kabhi Khushi Kabhie Gham", "Dil To Pagal Hai"],
    correctIndex: 0,
    trivia: "DDLJ has been running at Maratha Mandir cinema in Mumbai for over 25 consecutive years.",
  },
  {
    id: "tq_b3",
    category: "Bollywood",
    movieTitle: "3 Idiots",
    dialogue: "All Izz Well!",
    prompt: "Which Aamir Khan comedy-drama directed by Rajkumar Hirani popularized 'All Izz Well'?",
    options: ["3 Idiots", "PK", "Dangal", "Taare Zameen Par"],
    correctIndex: 0,
    trivia: "3 Idiots was a massive hit in East Asia, especially China and South Korea.",
  },
  {
    id: "tq_b4",
    category: "Bollywood",
    movieTitle: "Dangal",
    dialogue: "Mhaari chhoriyan chhoron se kam hain ke?",
    prompt: "Which sports biopic starring Aamir Khan as Mahavir Singh Phogat became India's highest grossing film worldwide?",
    options: ["Dangal", "Sultan", "Chak De! India", "Lagaan"],
    correctIndex: 0,
    trivia: "Dangal grossed over 2000 crore worldwide primarily driven by its historic Chinese box office run.",
  },
  {
    id: "tq_b5",
    category: "Bollywood",
    movieTitle: "Deewaar",
    dialogue: "Aaj mere paas gaadi hai, bungla hai, bank balance hai... tere paas kya hai?",
    prompt: "In Deewaar, Shashi Kapoor replied 'Mere paas maa hai' to which Amitabh Bachchan character?",
    options: ["Vijay", "Anthony", "Don", "Thakur"],
    correctIndex: 0,
    trivia: "Deewaar written by Salim-Javed cemented Amitabh Bachchan's 'Angry Young Man' image.",
  },
  {
    id: "tq_b6",
    category: "Bollywood",
    movieTitle: "Don",
    dialogue: "Don ko pakadna mushkil hi nahi, namumkin hai!",
    prompt: "Which classic crime action thriller starred Amitabh Bachchan in a double role?",
    options: ["Don", "Zanjeer", "Trishul", "Agneepath"],
    correctIndex: 0,
    trivia: "Don was later officially remade starring Shah Rukh Khan in 2006.",
  },
  {
    id: "tq_b7",
    category: "Bollywood",
    movieTitle: "Mr. India",
    dialogue: "Mogambo khush hua!",
    prompt: "Which villain played by Amrish Puri delivered the iconic phrase 'Mogambo khush hua'?",
    options: ["Mogambo", "Gabbar", "Shakaal", "Dr. Dang"],
    correctIndex: 0,
    trivia: "Mr. India directed by Shekhar Kapur featured Anil Kapoor and Sridevi.",
  },
  {
    id: "tq_b8",
    category: "Bollywood",
    movieTitle: "Lagaan",
    dialogue: "Sart manzoor hai!",
    prompt: "Which Oscar-nominated cricket period drama was directed by Ashutosh Gowariker?",
    options: ["Lagaan", "Swades", "Jodhaa Akbar", "Rang De Basanti"],
    correctIndex: 0,
    trivia: "Lagaan was only the third Indian film to be nominated for the Academy Award for Best Foreign Language Film.",
  },
  {
    id: "tq_b9",
    category: "Bollywood",
    movieTitle: "Om Shanti Om",
    dialogue: "Itni shiddat se maine tumhe paane ki koshish ki hai... ki har zarre ne mujhe tumse milane ki saazish ki hai!",
    prompt: "Which Shah Rukh Khan fantasy film directed by Farah Khan features this iconic monologue?",
    options: ["Om Shanti Om", "Main Hoon Na", "Chennai Express", "Kal Ho Naa Ho"],
    correctIndex: 0,
    trivia: "The film marked Deepika Padukone's Bollywood debut.",
  },
  {
    id: "tq_b10",
    category: "Bollywood",
    movieTitle: "Jab We Met",
    dialogue: "Main apni favourite hoon!",
    prompt: "Which Imtiaz Ali romantic comedy features Kareena Kapoor Khan as the effervescent Geet?",
    options: ["Jab We Met", "Love Aaj Kal", "Rockstar", "Tamasha"],
    correctIndex: 0,
    trivia: "Geet's dialogue and wardrobe became huge fashion trends across India.",
  },
  {
    id: "tq_b11",
    category: "Bollywood",
    movieTitle: "Gangs of Wasseypur",
    dialogue: "Baap ka, dada ka, bhai ka... sabka badla lega re tera Faizal!",
    prompt: "Which Anurag Kashyap crime epic stars Nawazuddin Siddiqui as Faizal Khan?",
    options: ["Gangs of Wasseypur", "Sacred Games", "Raman Raghav 2.0", "Badlapur"],
    correctIndex: 0,
    trivia: "Gangs of Wasseypur was screened in its entirety at the 2012 Cannes Directors' Fortnight.",
  },
  {
    id: "tq_b12",
    category: "Bollywood",
    movieTitle: "Chak De! India",
    dialogue: "Sattar Minute... 70 minute hain tumhare paas!",
    prompt: "Which sports drama stars Shah Rukh Khan as Indian Women's Hockey coach Kabir Khan?",
    options: ["Chak De! India", "Lagaan", "Dangal", "Sultan"],
    correctIndex: 0,
    trivia: "The 'Sattar Minute' speech is widely considered one of Indian cinema's greatest motivational speeches.",
  },
  {
    id: "tq_b13",
    category: "Bollywood",
    movieTitle: "Munna Bhai M.B.B.S.",
    dialogue: "Jaddu Ki Jhappi!",
    prompt: "Which Rajkumar Hirani comedy stars Sanjay Dutt as Munna and Arshad Warsi as Circuit?",
    options: ["Munna Bhai M.B.B.S.", "Lage Raho Munna Bhai", "3 Idiots", "PK"],
    correctIndex: 0,
    trivia: "The film won the National Film Award for Best Popular Film Providing Wholesome Entertainment.",
  },
  {
    id: "tq_b14",
    category: "Bollywood",
    movieTitle: "Zindagi Na Milegi Dobara",
    dialogue: "Seize the day my friend!",
    prompt: "Which Zoya Akhtar road-trip film stars Hrithik Roshan, Farhan Akhtar, and Abhay Deol in Spain?",
    options: ["Zindagi Na Milegi Dobara", "Dil Chahta Hai", "Rock On!!", "Yeh Jawaani Hai Deewani"],
    correctIndex: 0,
    trivia: "ZNMD significantly boosted Indian tourism to Spain following its release.",
  },
  {
    id: "tq_b15",
    category: "Bollywood",
    movieTitle: "Dil Chahta Hai",
    dialogue: "Hum dost the, hain aur rahenge!",
    prompt: "Which 2001 Farhan Akhtar directorial debut revolutionized youth coming-of-age cinema?",
    options: ["Dil Chahta Hai", "ZNMD", "Rock On!!", "Lakshya"],
    correctIndex: 0,
    trivia: "Starring Aamir Khan, Saif Ali Khan, and Akshaye Khanna, it won the National Film Award for Best Feature Film in Hindi.",
  },
  {
    id: "tq_b16",
    category: "Bollywood",
    movieTitle: "Yeh Jawaani Hai Deewani",
    dialogue: "Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bas rukna nahi chahta!",
    prompt: "Which Ayan Mukerji blockbuster stars Ranbir Kapoor as Bunny and Deepika Padukone as Naina?",
    options: ["Yeh Jawaani Hai Deewani", "Wake Up Sid", "Rockstar", "Tamasha"],
    correctIndex: 0,
    trivia: "The film scored massive box-office collections and Pritam's soundtrack was a mega hit.",
  },
  {
    id: "tq_b17",
    category: "Bollywood",
    movieTitle: "Rockstar",
    dialogue: "Pata hai... yahan se bahut door, galat aur sahi ke paar, ek maidan hai... main wahan milunga tujhe!",
    prompt: "Which Imtiaz Ali musical drama features Ranbir Kapoor as Jordan (Janardhan Jakhar)?",
    options: ["Rockstar", "Tamasha", "Barfi!", "Sanju"],
    correctIndex: 0,
    trivia: "A.R. Rahman's music soundtrack for Rockstar won all major music awards in India.",
  },
  {
    id: "tq_b18",
    category: "Bollywood",
    movieTitle: "Barfi!",
    dialogue: "Life mein sabse bada risk hota hai... kisi risk ko na lena!",
    prompt: "Which Anurag Basu romantic comedy-drama starred Ranbir Kapoor as a hearing/speech-impaired man?",
    options: ["Barfi!", "Jagga Jasoos", "Tamasha", "Sanju"],
    correctIndex: 0,
    trivia: "Barfi! was India's official entry for the Best Foreign Language Film at the 85th Academy Awards.",
  },
  {
    id: "tq_b19",
    category: "Bollywood",
    movieTitle: "Queen",
    dialogue: "Mera honeymoon mera akela hai!",
    prompt: "Which Vikas Bahl comedy-drama stars Kangana Ranaut going on her solo honeymoon to Paris and Amsterdam?",
    options: ["Queen", "Tanu Weds Manu", "Piku", "English Vinglish"],
    correctIndex: 0,
    trivia: "Kangana Ranaut won the National Film Award for Best Actress for Queen.",
  },
  {
    id: "tq_b20",
    category: "Bollywood",
    movieTitle: "Piku",
    dialogue: "Motion se hi Emotion juda hai!",
    prompt: "Which Shoojit Sircar comedy-drama stars Amitabh Bachchan, Deepika Padukone, and Irrfan Khan?",
    options: ["Piku", "October", "Vicky Donor", "Hindi Medium"],
    correctIndex: 0,
    trivia: "Amitabh Bachchan won his fourth National Film Award for Best Actor for Piku.",
  },
  {
    id: "tq_b21",
    category: "Bollywood",
    movieTitle: "Andhadhun",
    dialogue: "Kya aapko sach mein lagta hai main andha hoon?",
    prompt: "Which Sriram Raghavan neo-noir black comedy stars Ayushmann Khurrana as a blind pianist?",
    options: ["Andhadhun", "Article 15", "Badhaai Ho", "Bala"],
    correctIndex: 0,
    trivia: "Andhadhun won three National Film Awards including Best Feature Film in Hindi.",
  },
  {
    id: "tq_b22",
    category: "Bollywood",
    movieTitle: "Stree",
    dialogue: "O Stree Kal Aana!",
    prompt: "Which horror-comedy starring Rajkummar Rao and Shraddha Kapoor is set in Chanderi village?",
    options: ["Stree", "Roohi", "Bhediya", "Munjya"],
    correctIndex: 0,
    trivia: "Stree launched the successful Maddock Supernatural Universe.",
  },
  {
    id: "tq_b23",
    category: "Bollywood",
    movieTitle: "Uri: The Surgical Strike",
    dialogue: "How's the Josh? High, Sir!",
    prompt: "Which Vicky Kaushal military action film introduced the popular catchphrase 'How's the Josh?'",
    options: ["Uri: The Surgical Strike", "Raazi", "Shershaah", "Border"],
    correctIndex: 0,
    trivia: "Vicky Kaushal won the National Film Award for Best Actor.",
  },
  {
    id: "tq_b24",
    category: "Bollywood",
    movieTitle: "Shershaah",
    dialogue: "Yeh Dil Maange More!",
    prompt: "Which biopic stars Sidharth Malhotra as Captain Vikram Batra PVC during the 1999 Kargil War?",
    options: ["Shershaah", "Uri", "Border", "LOC Kargil"],
    correctIndex: 0,
    trivia: "Shershaah won the Special Jury Award at the 69th National Film Awards.",
  },
  {
    id: "tq_b25",
    category: "Bollywood",
    movieTitle: "Jawan",
    dialogue: "Bete ko haath lagane se pehle, baap se baat kar!",
    prompt: "Which 2023 Atlee action thriller starring Shah Rukh Khan broke Hindi box office records?",
    options: ["Jawan", "Pathaan", "Dunki", "War"],
    correctIndex: 0,
    trivia: "Jawan grossed over 1140 crore worldwide.",
  },
  {
    id: "tq_b26",
    category: "Bollywood",
    movieTitle: "Pathaan",
    dialogue: "Apni kursi ki petiyann baandh lo, mausam bigadne wala hai!",
    prompt: "Which YRF Spy Universe film marked Shah Rukh Khan's grand theatrical comeback after 4 years?",
    options: ["Pathaan", "Jawan", "Tiger 3", "War"],
    correctIndex: 0,
    trivia: "Pathaan grossed over 1050 crore worldwide.",
  },
  {
    id: "tq_b27",
    category: "Bollywood",
    movieTitle: "Animal",
    dialogue: "Sunai de raha hai, behera nahi hoon main!",
    prompt: "Which Sandeep Reddy Vanga action drama starring Ranbir Kapoor as Rannvijay became a global blockbuster?",
    options: ["Animal", "Kabir Singh", "Sanju", "Rockstar"],
    correctIndex: 0,
    trivia: "Animal grossed over 900 crore worldwide.",
  },
  {
    id: "tq_b28",
    category: "Bollywood",
    movieTitle: "12th Fail",
    dialogue: "Restart!",
    prompt: "Which Vidhu Vinod Chopra biographical film stars Vikrant Massey as IPS officer Manoj Kumar Sharma?",
    options: ["12th Fail", "Super 30", "Chhichhore", "Taare Zameen Par"],
    correctIndex: 0,
    trivia: "12th Fail won Best Film and Best Director at the 69th Filmfare Awards.",
  },
  {
    id: "tq_b29",
    category: "Bollywood",
    movieTitle: "Bhool Bhulaiyaa",
    dialogue: "Aami Je Tomar!",
    prompt: "Which Priyadarshan psychological horror-comedy stars Akshay Kumar as Psychiatrist Dr. Aditya Shrivastav?",
    options: ["Bhool Bhulaiyaa", "Stree", "Welcome", "Hera Pheri"],
    correctIndex: 0,
    trivia: "Vidya Balan's portrayal of Manjulika remains iconic in Indian pop culture.",
  },
  {
    id: "tq_b30",
    category: "Bollywood",
    movieTitle: "Hera Pheri",
    dialogue: "Ye Baburao ka style hai!",
    prompt: "Which Priyadarshan comedy featuring Paresh Rawal (Baburao), Akshay Kumar (Raju), and Suniel Shetty (Shyam) is a legendary meme engine?",
    options: ["Hera Pheri", "Phir Hera Pheri", "Welcome", "Awara Paagal Deewana"],
    correctIndex: 0,
    trivia: "Hera Pheri is voted among the greatest Hindi comedy films ever made.",
  },

  // ==================== HOLLYWOOD (30 Questions) ====================
  {
    id: "tq_h1",
    category: "Hollywood",
    movieTitle: "Avengers: Endgame",
    dialogue: "I love you 3000!",
    prompt: "Which MCU blockbuster features Iron Man (Tony Stark) delivering the line 'I love you 3000'?",
    options: ["Avengers: Endgame", "Avengers: Infinity War", "Iron Man 3", "Captain America: Civil War"],
    correctIndex: 0,
    trivia: "Avengers: Endgame became the highest-grossing film of all time upon release in 2019.",
  },
  {
    id: "tq_h2",
    category: "Hollywood",
    movieTitle: "The Dark Knight",
    dialogue: "Why so serious?",
    prompt: "Which Heath Ledger performance as The Joker coined the iconic catchphrase 'Why so serious?'",
    options: ["The Dark Knight", "Batman Begins", "The Dark Knight Rises", "Joker"],
    correctIndex: 0,
    trivia: "Heath Ledger posthumously won the Academy Award for Best Supporting Actor.",
  },
  {
    id: "tq_h3",
    category: "Hollywood",
    movieTitle: "Titanic",
    dialogue: "I'm the king of the world!",
    prompt: "Which James Cameron romantic epic stars Leonardo DiCaprio shouting this from the ship bow?",
    options: ["Titanic", "Avatar", "Inception", "The Great Gatsby"],
    correctIndex: 0,
    trivia: "Titanic won 11 Academy Awards tying the record for most Oscars won by a single film.",
  },
  {
    id: "tq_h4",
    category: "Hollywood",
    movieTitle: "Inception",
    dialogue: "An idea is like a virus. Resilient. Highly contagious.",
    prompt: "Which Christopher Nolan sci-fi thriller deals with dream invasion and totems?",
    options: ["Inception", "Interstellar", "Tenet", "The Prestige"],
    correctIndex: 0,
    trivia: "The ambiguous spinning top ending remains one of cinema's most debated moments.",
  },
  {
    id: "tq_h5",
    category: "Hollywood",
    movieTitle: "Interstellar",
    dialogue: "Love is the one thing that transcends time and space.",
    prompt: "Which Christopher Nolan epic stars Matthew McConaughey traveling through a wormhole near Saturn?",
    options: ["Interstellar", "Inception", "Gravity", "The Martian"],
    correctIndex: 0,
    trivia: "Theoretical physicist Kip Thorne served as scientific consultant and executive producer.",
  },
  {
    id: "tq_h6",
    category: "Hollywood",
    movieTitle: "Avatar",
    dialogue: "I see you.",
    prompt: "Which James Cameron sci-fi epic set on the moon Pandora became the highest-grossing film of all time?",
    options: ["Avatar", "Avatar: The Way of Water", "Titanic", "Aliens"],
    correctIndex: 0,
    trivia: "Avatar pioneered 3D camera technology and motion capture visual effects.",
  },
  {
    id: "tq_h7",
    category: "Hollywood",
    movieTitle: "Star Wars: The Empire Strikes Back",
    dialogue: "No, I am your father!",
    prompt: "Which iconic villain Darth Vader delivered this historic twist reveal to Luke Skywalker?",
    options: ["Darth Vader", "Emperor Palpatine", "Kylo Ren", "Darth Maul"],
    correctIndex: 0,
    trivia: "The line is frequently misquoted pop-culturally as 'Luke, I am your father'.",
  },
  {
    id: "tq_h8",
    category: "Hollywood",
    movieTitle: "The Terminator",
    dialogue: "I'll be back!",
    prompt: "Which Arnold Schwarzenegger cyborg catchphrase became one of Hollywood's most legendary quotes?",
    options: ["The Terminator", "Terminator 2: Judgment Day", "Predator", "Commando"],
    correctIndex: 0,
    trivia: "Director James Cameron wrote the line 'I'll be back' into the script without anticipating its pop culture legacy.",
  },
  {
    id: "tq_h9",
    category: "Hollywood",
    movieTitle: "Jurassic Park",
    dialogue: "Life finds a way.",
    prompt: "Which Steven Spielberg blockbuster features Jeff Goldblum (Dr. Ian Malcolm) saying 'Life finds a way'?",
    options: ["Jurassic Park", "The Lost World", "Jurassic World", "Independence Day"],
    correctIndex: 0,
    trivia: "Jurassic Park revolutionized CGI dinos alongside practical animatronics.",
  },
  {
    id: "tq_h10",
    category: "Hollywood",
    movieTitle: "The Matrix",
    dialogue: "You take the blue pill... you take the red pill...",
    prompt: "Which sci-fi classic directed by the Wachowskis features Keanu Reeves as Neo?",
    options: ["The Matrix", "The Matrix Reloaded", "John Wick", "Constantine"],
    correctIndex: 0,
    trivia: "The Matrix introduced 'bullet time' visual effects to mainstream cinema.",
  },
  {
    id: "tq_h11",
    category: "Hollywood",
    movieTitle: "Forrest Gump",
    dialogue: "Life is like a box of chocolates. You never know what you're gonna get.",
    prompt: "Which Tom Hanks Oscar-winning film features this famous bench monologue?",
    options: ["Forrest Gump", "Cast Away", "Saving Private Ryan", "The Terminal"],
    correctIndex: 0,
    trivia: "Forrest Gump won six Academy Awards including Best Picture and Best Actor.",
  },
  {
    id: "tq_h12",
    category: "Hollywood",
    movieTitle: "The Godfather",
    dialogue: "I'm gonna make him an offer he can't refuse.",
    prompt: "Which Marlon Brando (Vito Corleone) line ranks #2 on the AFI's 100 Years... 100 Movie Quotes?",
    options: ["The Godfather", "The Godfather Part II", "Scarface", "Goodfellas"],
    correctIndex: 0,
    trivia: "Francis Ford Coppola's film won the Academy Award for Best Picture.",
  },
  {
    id: "tq_h13",
    category: "Hollywood",
    movieTitle: "Gladiator",
    dialogue: "My name is Maximus Decimus Meridius... and I will have my vengeance!",
    prompt: "Which Ridley Scott historical epic stars Russell Crowe as the betrayed Roman general?",
    options: ["Gladiator", "Spartacus", "Troy", "300"],
    correctIndex: 0,
    trivia: "Gladiator won five Academy Awards including Best Picture and Best Actor.",
  },
  {
    id: "tq_h14",
    category: "Hollywood",
    movieTitle: "The Shawshank Redemption",
    dialogue: "Get busy living, or get busy dying.",
    prompt: "Which film starring Tim Robbins (Andy Dufresne) and Morgan Freeman (Red) holds the #1 spot on IMDb?",
    options: ["The Shawshank Redemption", "The Green Mile", "Pulp Fiction", "Se7en"],
    correctIndex: 0,
    trivia: "Based on Stephen King's novella, it is widely regarded as one of the greatest films ever made.",
  },
  {
    id: "tq_h15",
    category: "Hollywood",
    movieTitle: "Harry Potter and the Sorcerer's Stone",
    dialogue: "You're a wizard, Harry!",
    prompt: "Which fantasy film introduced Daniel Radcliffe as the Boy Who Lived?",
    options: ["Harry Potter 1", "Harry Potter 2", "Harry Potter 3", "Fantastic Beasts"],
    correctIndex: 0,
    trivia: "Hagrid (Robbie Coltrane) delivered the famous line when visiting Harry on his 11th birthday.",
  },
  {
    id: "tq_h16",
    category: "Hollywood",
    movieTitle: "The Lord of the Rings: The Fellowship of the Ring",
    dialogue: "One does not simply walk into Mordor.",
    prompt: "Which Sean Bean (Boromir) quote became one of the internet's most famous meme templates?",
    options: ["The Fellowship of the Ring", "The Two Towers", "The Return of the King", "The Hobbit"],
    correctIndex: 0,
    trivia: "Peter Jackson's trilogy won 17 Academy Awards in total.",
  },
  {
    id: "tq_h17",
    category: "Hollywood",
    movieTitle: "Pulp Fiction",
    dialogue: "Say 'what' again, I dare you!",
    prompt: "Which Quentin Tarantino crime masterpiece features Samuel L. Jackson as Jules Winnfield?",
    options: ["Pulp Fiction", "Django Unchained", "Reservoir Dogs", "Kill Bill"],
    correctIndex: 0,
    trivia: "Pulp Fiction won the Palme d'Or at the 1994 Cannes Film Festival.",
  },
  {
    id: "tq_h18",
    category: "Hollywood",
    movieTitle: "Pirates of the Caribbean: The Curse of the Black Pearl",
    dialogue: "This is the day you will always remember as the day you almost caught Captain Jack Sparrow!",
    prompt: "Which Johnny Depp character popularized this pirate line?",
    options: ["Captain Jack Sparrow", "Hector Barbossa", "Davy Jones", "Will Turner"],
    correctIndex: 0,
    trivia: "Depp earned an Oscar nomination for Best Actor for his eccentric performance.",
  },
  {
    id: "tq_h19",
    category: "Hollywood",
    movieTitle: "Spider-Man",
    dialogue: "With great power comes great responsibility.",
    prompt: "Which Tobey Maguire superhero origin film introduced Uncle Ben's iconic wisdom?",
    options: ["Spider-Man (2002)", "Spider-Man 2", "Spider-Man: No Way Home", "The Amazing Spider-Man"],
    correctIndex: 0,
    trivia: "Directed by Sam Raimi, it was the first film to reach $100M in a single weekend.",
  },
  {
    id: "tq_h20",
    category: "Hollywood",
    movieTitle: "Iron Man",
    dialogue: "I am Iron Man.",
    prompt: "Which 2008 Robert Downey Jr. film kicked off the Marvel Cinematic Universe?",
    options: ["Iron Man", "The Avengers", "Iron Man 2", "Captain America"],
    correctIndex: 0,
    trivia: "Robert Downey Jr. improvised the closing line 'I am Iron Man'.",
  },
  {
    id: "tq_h21",
    category: "Hollywood",
    movieTitle: "The Lion King",
    dialogue: "Hakuna Matata!",
    prompt: "Which Disney animated classic features Timon and Pumbaa singing 'Hakuna Matata'?",
    options: ["The Lion King", "Aladdin", "Beauty and the Beast", "The Jungle Book"],
    correctIndex: 0,
    trivia: "The Lion King won two Academy Awards for its music composed by Hans Zimmer & Elton John.",
  },
  {
    id: "tq_h22",
    category: "Hollywood",
    movieTitle: "Oppenheimer",
    dialogue: "Now I am become Death, the destroyer of worlds.",
    prompt: "Which 2023 Christopher Nolan biopic starring Cillian Murphy won 7 Academy Awards including Best Picture?",
    options: ["Oppenheimer", "Dunkirk", "Tenet", "Interstellar"],
    correctIndex: 0,
    trivia: "Cillian Murphy won the Academy Award for Best Actor for portraying J. Robert Oppenheimer.",
  },
  {
    id: "tq_h23",
    category: "Hollywood",
    movieTitle: "Barbie",
    dialogue: "Sublime!",
    prompt: "Which 2023 Greta Gerwig comedy-fantasy starring Margot Robbie and Ryan Gosling grossed $1.44 billion?",
    options: ["Barbie", "La La Land", "Little Women", "Mean Girls"],
    correctIndex: 0,
    trivia: "Barbie was the highest-grossing film of 2023 worldwide.",
  },
  {
    id: "tq_h24",
    category: "Hollywood",
    movieTitle: "Top Gun: Maverick",
    dialogue: "Don't think, just do!",
    prompt: "Which Tom Cruise aerial action sequel brought audiences back to theaters post-pandemic grossing $1.49 billion?",
    options: ["Top Gun: Maverick", "Mission: Impossible - Fallout", "Edge of Tomorrow", "Top Gun (1986)"],
    correctIndex: 0,
    trivia: "Tom Cruise and the cast flew real F/A-18 fighter jets for the aerial filming sequences.",
  },
  {
    id: "tq_h25",
    category: "Hollywood",
    movieTitle: "Black Panther",
    dialogue: "Wakanda Forever!",
    prompt: "Which Chadwick Boseman Marvel film set in the fictional African nation of Wakanda earned a Best Picture Oscar nomination?",
    options: ["Black Panther", "Avengers: Infinity War", "Captain America: Civil War", "Doctor Strange"],
    correctIndex: 0,
    trivia: "Black Panther was the first superhero film to receive a Best Picture Academy Award nomination.",
  },
  {
    id: "tq_h26",
    category: "Hollywood",
    movieTitle: "Joker",
    dialogue: "I used to think that my life was a tragedy, but now I realize, it's a comedy.",
    prompt: "Which Joaquin Phoenix psychological thriller won the Golden Lion at Venice Film Festival?",
    options: ["Joker", "The Dark Knight", "Her", "Napoleon"],
    correctIndex: 0,
    trivia: "Joaquin Phoenix won the Academy Award for Best Actor for playing Arthur Fleck.",
  },
  {
    id: "tq_h27",
    category: "Hollywood",
    movieTitle: "Dune: Part Two",
    dialogue: "Long live the fighters!",
    prompt: "Which Denis Villeneuve sci-fi epic stars Timothée Chalamet as Paul Atreides on Arrakis?",
    options: ["Dune: Part Two", "Dune (2021)", "Blade Runner 2049", "Arrival"],
    correctIndex: 0,
    trivia: "The film was universally praised for its visual scope and Hans Zimmer's score.",
  },
  {
    id: "tq_h28",
    category: "Hollywood",
    movieTitle: "Mission: Impossible - Fallout",
    dialogue: "What's done is done when we say it's done!",
    prompt: "Which action spy film features Tom Cruise performing a HALO jump and piloting a helicopter?",
    options: ["Mission: Impossible - Fallout", "Rogue Nation", "Ghost Protocol", "Dead Reckoning"],
    correctIndex: 0,
    trivia: "Tom Cruise broke his ankle while jumping between rooftops during filming in London.",
  },
  {
    id: "tq_h29",
    category: "Hollywood",
    movieTitle: "La La Land",
    dialogue: "Here's to the fools who dream!",
    prompt: "Which Damien Chazelle musical starring Ryan Gosling and Emma Stone won 6 Academy Awards?",
    options: ["La La Land", "Whiplash", "Babylon", "First Man"],
    correctIndex: 0,
    trivia: "Emma Stone won the Academy Award for Best Actress for her role as Mia.",
  },
  {
    id: "tq_h30",
    category: "Hollywood",
    movieTitle: "Mad Max: Fury Road",
    dialogue: "Oh, what a day... what a lovely day!",
    prompt: "Which George Miller post-apocalyptic action masterpiece starring Tom Hardy and Charlize Theron won 6 Oscars?",
    options: ["Mad Max: Fury Road", "Furiosa", "Waterworld", "The Book of Eli"],
    correctIndex: 0,
    trivia: "Over 80% of the visual effects in Fury Road were practical stunts and real vehicle crashes.",
  },
];
