import type { TeluguCinemaluSet } from "@shared/types.js";

/**
 * Rounds 2-4 content, grouped into playable sets. A game draws one whole set,
 * so questions inside a set should not give each other away.
 *
 * The brief asks for ten sets. Two are authored here. The remaining eight are
 * deliberately left for you rather than filled with guesses: dialogue
 * attribution in particular is where a hand-authored bank goes wrong, and a
 * mis-credited line marks a correct player wrong. `content.test.ts` enforces
 * the shape of every set that exists, so adding more is mechanical — copy a
 * block, keep the difficulty ladder, and CI will reject anything malformed.
 */

const set1: TeluguCinemaluSet = {
  id: "set1",
  narration: [
    {
      id: "s1_n1",
      difficulty: "easy",
      body: "A young man raised by a tribal family discovers he is heir to the throne, and uncovers why his father was betrayed by the man who raised him as a slave.",
      prompt: "Which film is being described?",
      options: ["Baahubali: The Beginning", "Magadheera", "Rudhramadevi", "Sye Raa Narasimha Reddy"],
      correctIndex: 0,
    },
    {
      id: "s1_n2",
      difficulty: "easy",
      body: "In the 1920s, a tribal guardian searching for a girl taken by the British and a colonial officer with a hidden agenda become close friends, neither knowing the other's true purpose.",
      prompt: "Which film is being described?",
      options: ["RRR", "Baahubali 2", "Sye Raa Narasimha Reddy", "Acharya"],
      correctIndex: 0,
    },
    {
      id: "s1_n3",
      difficulty: "moderate",
      body: "A daily-wage coolie in a red sandalwood smuggling operation climbs from the bottom of the syndicate to its head, refusing to lower himself before anyone.",
      prompt: "Which film is being described?",
      options: ["Pushpa: The Rise", "Rangasthalam", "Sarrainodu", "Naa Peru Surya"],
      correctIndex: 0,
    },
    {
      id: "s1_n4",
      difficulty: "hard",
      body: "A partially deaf young man in a 1980s village helps his idealistic elder brother take on the long-entrenched president of the local cooperative society.",
      prompt: "Which film is being described?",
      options: ["Rangasthalam", "Uppena", "Jathi Ratnalu", "Palasa 1978"],
      correctIndex: 0,
    },
    {
      id: "s1_n5",
      difficulty: "extreme",
      body: "A man murdered for loving a woman his rival wanted is reborn, and sets about avenging his own death.",
      prompt: "Which film is being described?",
      options: ["Eega", "Magadheera", "Anaganaga O Dheerudu", "Yamadonga"],
      correctIndex: 0,
      trivia: "Directed by S. S. Rajamouli, with Nani and Samantha in the lead roles.",
    },
  ],
  dialogue: [
    {
      id: "s1_d1",
      difficulty: "easy",
      body: "\"Okkasari commit ayithe naa maata nenae vinanu.\"",
      prompt: "Which film features this dialogue?",
      options: ["Pokiri", "Businessman", "Athadu", "Dookudu"],
      correctIndex: 0,
    },
    {
      id: "s1_d2",
      difficulty: "easy",
      body: "\"Thaggedhe le.\"",
      prompt: "Which film made this line a catchphrase?",
      options: ["Pushpa: The Rise", "Sarrainodu", "Race Gurram", "Ala Vaikunthapurramuloo"],
      correctIndex: 0,
    },
    {
      id: "s1_d3",
      difficulty: "moderate",
      body: "\"Naaku konchem thikkundi, kaani daaniko lekkundi.\"",
      prompt: "Which actor delivers this line?",
      options: ["Pawan Kalyan", "Mahesh Babu", "Allu Arjun", "NTR Jr."],
      correctIndex: 0,
    },
    {
      id: "s1_d4",
      difficulty: "hard",
      body: "\"Pushpa ante flower anukunnava? ______\"",
      prompt: "Complete the dialogue.",
      options: ["Fire", "Thunder", "Storm", "Danger"],
      correctIndex: 0,
    },
    {
      id: "s1_d5",
      difficulty: "extreme",
      body: "The first Baahubali film closes on a single unanswered question that carried audiences to the sequel.",
      prompt: "What was that question?",
      options: [
        "Why did Kattappa kill Baahubali?",
        "Who is Sivagami's real son?",
        "Where is Devasena imprisoned?",
        "Who rules Mahishmati?",
      ],
      correctIndex: 0,
    },
  ],
  combination: [
    {
      id: "s1_c1",
      difficulty: "easy",
      body: "Ram Charan + Kajal Aggarwal + M. M. Keeravani",
      prompt: "Which film do these three point to?",
      options: ["Magadheera", "Rangasthalam", "Orange", "Racha"],
      correctIndex: 0,
    },
    {
      id: "s1_c2",
      difficulty: "easy",
      body: "Allu Arjun + Rashmika Mandanna + Devi Sri Prasad",
      prompt: "Which film do these three point to?",
      options: ["Pushpa: The Rise", "Ala Vaikunthapurramuloo", "Sarrainodu", "Duvvada Jagannadham"],
      correctIndex: 0,
    },
    {
      id: "s1_c3",
      difficulty: "easy",
      body: "Naga Chaitanya + Kajal Aggarwal + Devi Sri Prasad",
      prompt: "Which film do these three point to?",
      options: ["Dhada", "100% Love", "Josh", "Bejawada"],
      correctIndex: 0,
    },
    {
      id: "s1_c4",
      difficulty: "moderate",
      body: "Dammu + NTR Jr. + Trisha",
      prompt: "Who composed the music?",
      options: ["M. M. Keeravani", "Devi Sri Prasad", "Thaman S", "Mani Sharma"],
      correctIndex: 0,
    },
    {
      id: "s1_c5",
      difficulty: "moderate",
      body: "Prabhas + Anushka Shetty + Devi Sri Prasad",
      prompt: "Which film do these three point to?",
      options: ["Mirchi", "Billa", "Baahubali", "Mr. Perfect"],
      correctIndex: 0,
    },
    {
      id: "s1_c6",
      difficulty: "hard",
      body: "Pokiri + Mahesh Babu + Ileana",
      prompt: "Who composed the music?",
      options: ["Mani Sharma", "Devi Sri Prasad", "Thaman S", "M. M. Keeravani"],
      correctIndex: 0,
    },
    {
      id: "s1_c7",
      difficulty: "hard",
      body: "Ram Charan + Samantha + Devi Sri Prasad",
      prompt: "Which film do these three point to?",
      options: ["Rangasthalam", "Magadheera", "Dhruva", "Yevadu"],
      correctIndex: 0,
    },
    {
      id: "s1_c8",
      difficulty: "extreme",
      body: "Baahubali + Prabhas + Anushka Shetty",
      prompt: "Who composed the music?",
      options: ["M. M. Keeravani", "Devi Sri Prasad", "Thaman S", "A. R. Rahman"],
      correctIndex: 0,
    },
  ],
};

const set2: TeluguCinemaluSet = {
  id: "set2",
  narration: [
    {
      id: "s2_n1",
      difficulty: "easy",
      body: "Four years in an engineering college, following a group of friends from nervous first-year arrivals to graduation, and the romances that survive or don't.",
      prompt: "Which film is being described?",
      options: ["Happy Days", "Kotha Bangaru Lokam", "Life Is Beautiful", "Pelli Choopulu"],
      correctIndex: 0,
    },
    {
      id: "s2_n2",
      difficulty: "easy",
      body: "A brilliant but volatile surgeon spirals into self-destruction after being separated from the woman he loves.",
      prompt: "Which film is being described?",
      options: ["Arjun Reddy", "Dear Comrade", "Ninnu Kori", "Taxiwaala"],
      correctIndex: 0,
    },
    {
      id: "s2_n3",
      difficulty: "moderate",
      body: "A confident young man raised in a middle-class home discovers he was swapped at birth, and takes a job in the wealthy household that should have been his in order to set the family right.",
      prompt: "Which film is being described?",
      options: [
        "Ala Vaikunthapurramuloo",
        "Attarintiki Daredi",
        "Srimanthudu",
        "Seethamma Vakitlo Sirimalle Chettu",
      ],
      correctIndex: 0,
    },
    {
      id: "s2_n4",
      difficulty: "hard",
      body: "A cricketer who quit the game returns to the field in his late thirties, driven by a promise to buy his young son a jersey.",
      prompt: "Which film is being described?",
      options: ["Jersey", "Ghazi", "Majili", "Sye"],
      correctIndex: 0,
    },
    {
      id: "s2_n5",
      difficulty: "extreme",
      body: "A spirited young woman rooted in her Telangana farming family falls for an NRI, and the romance strains against how unwilling she is to leave her land.",
      prompt: "Which film is being described?",
      options: ["Fidaa", "Love Story", "Uppena", "Nuvvostanante Nenoddantana"],
      correctIndex: 0,
    },
  ],
  dialogue: [
    {
      id: "s2_d1",
      difficulty: "easy",
      body: "\"Thaggedhe le.\"",
      prompt: "Which actor made this line famous?",
      options: ["Allu Arjun", "Ram Charan", "NTR Jr.", "Prabhas"],
      correctIndex: 0,
    },
    {
      id: "s2_d2",
      difficulty: "easy",
      body: "\"Okkasari commit ayithe naa maata nenae vinanu.\"",
      prompt: "Which actor delivers this line?",
      options: ["Mahesh Babu", "Pawan Kalyan", "Ravi Teja", "Nagarjuna"],
      correctIndex: 0,
    },
    {
      id: "s2_d3",
      difficulty: "moderate",
      body: "\"Naaku konchem thikkundi, kaani daaniko lekkundi.\"",
      prompt: "Which film features this dialogue?",
      options: ["Gabbar Singh", "Jalsa", "Attarintiki Daredi", "Kushi"],
      correctIndex: 0,
    },
    {
      id: "s2_d4",
      difficulty: "hard",
      body: "\"Jai ______!\" — the war cry of the kingdom at the centre of Rajamouli's two-part epic.",
      prompt: "Complete the chant.",
      options: ["Mahishmati", "Kuntala", "Vijayanagara", "Kalinga"],
      correctIndex: 0,
    },
    {
      id: "s2_d5",
      difficulty: "extreme",
      body: "\"Pushpa ante flower anukunnava? Fire.\"",
      prompt: "Who directed the film this line is from?",
      options: ["Sukumar", "Trivikram Srinivas", "Koratala Siva", "Harish Shankar"],
      correctIndex: 0,
    },
  ],
  combination: [
    {
      id: "s2_c1",
      difficulty: "easy",
      body: "Prabhas + Rana Daggubati + M. M. Keeravani",
      prompt: "Which film do these three point to?",
      options: ["Baahubali", "Mirchi", "Chatrapathi", "Billa"],
      correctIndex: 0,
    },
    {
      id: "s2_c2",
      difficulty: "easy",
      body: "Ala Vaikunthapurramuloo + Allu Arjun + Pooja Hegde",
      prompt: "Who directed it?",
      options: ["Trivikram Srinivas", "Sukumar", "Harish Shankar", "Vamshi Paidipally"],
      correctIndex: 0,
    },
    {
      id: "s2_c3",
      difficulty: "easy",
      body: "Rangasthalam + Ram Charan + Samantha",
      prompt: "Who directed it?",
      options: ["Sukumar", "S. S. Rajamouli", "Koratala Siva", "Trivikram Srinivas"],
      correctIndex: 0,
    },
    {
      id: "s2_c4",
      difficulty: "moderate",
      body: "Mahesh Babu + Trisha + Mani Sharma",
      prompt: "Which Trivikram film do these three point to?",
      options: ["Athadu", "Khaleja", "Nuvvu Naaku Nachav", "Varsham"],
      correctIndex: 0,
    },
    {
      id: "s2_c5",
      difficulty: "moderate",
      body: "Ye Maaya Chesave + Naga Chaitanya + Samantha",
      prompt: "Who composed the music?",
      options: ["A. R. Rahman", "Devi Sri Prasad", "Mickey J Meyer", "Thaman S"],
      correctIndex: 0,
    },
    {
      id: "s2_c6",
      difficulty: "hard",
      body: "Mahesh Babu + Venkatesh + Mickey J Meyer",
      prompt: "Which 2013 family drama do these point to?",
      options: [
        "Seethamma Vakitlo Sirimalle Chettu",
        "Manam",
        "Drushyam",
        "Bhaskar Oka Rascal",
      ],
      correctIndex: 0,
    },
    {
      id: "s2_c7",
      difficulty: "hard",
      body: "Sai Pallavi + Varun Tej + Sekhar Kammula",
      prompt: "Which film do these three point to?",
      options: ["Fidaa", "Love Story", "Antariksham 9000 KMPH", "Tholi Prema"],
      correctIndex: 0,
    },
    {
      id: "s2_c8",
      difficulty: "extreme",
      body: "Jersey + Nani + Shraddha Srinath",
      prompt: "Who composed the music?",
      options: ["Anirudh Ravichander", "Devi Sri Prasad", "Thaman S", "Mickey J Meyer"],
      correctIndex: 0,
    },
  ],
};

export const TELUGUCINEMALU_SETS: TeluguCinemaluSet[] = [set1, set2];
